name = "istic-catalog-ai"
compatibility_date = "2024-03-12"
kv_namespaces = [
  { binding = "cache", id = "cache" }
]

[vars]
GITHUB_OWNER = "FushenYang"
GITHUB_REPO = "istic.catalog.ai"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "prod-ai-db"
database_id = "095f5702-cfe6-4967-b9dc-37c6e0559322"
preview_database_id = "DB"