import Papa from 'papaparse';

const csv_json = (csv: string): Array<Object> => {
	const lines = Papa.parse<string[]>(csv.trim());
	const headers = lines.data[0];
	const content = lines.data.slice(1);
	const jsonResult = content.map(line => {
		let currentLine = line;
		let jsonObj: { [key: string]: string } = {};
		headers.forEach((header: string, i) => {
			jsonObj[header] = currentLine[i];
		});
		return jsonObj;
	});
	return jsonResult; //JSON.stringify(jsonResult)
};

const csvdata: string = `
degree_prog_id,inst_name_cn,inst_name_en,intro_cn,inst_type,country,rank,prog_name,is_indep,prog_type,prog_url,school,host_inst,awards_or_abet,apply_url,degree,duration,joint,min_credit,thesis,prog_goal,prog_outcome,has_culm_act,internship ,has_minor,course_url,faculty,stu_hb_url
1,卡内基梅隆大学,Carnegie Mellon University,"卡内基梅隆大学（Carnegie Mellon University），简称CMU，坐落在美国宾夕法尼亚州的匹兹堡，是一所拥有13,600名在校学生和1,423名教职及科研人员的世界顶尖学府，美国25所新常春藤盟校之一。除了匹兹堡，卡内基梅隆大学在美国硅谷以及卡塔尔设有分校，并且其在世界各地均设有合作研究机构，包括纽约、洛杉矶、华盛顿特区、中国、澳大利亚、葡萄牙、卢旺达等。该校拥有享誉全球的计算机学院和戏剧学院，其艺术学院，商学院，工程院以及公共管理学院等也都在全美名列前茅。CMU由工业家兼慈善家安德鲁·卡耐基于1900年创建，当时名为卡内基技术学校，1912年改名为卡内基梅隆大学，开始向以研究为主的美国重点大学转变。CMU位列2020U.S. News美国最佳大学排名第25名，包括最佳创新大学第7位，商科全美第5，工程院第6（本科），计算机学院第2。其量化金融项目（MSCF）常年在全美名列前3。2020QS世界大学学科排名中，其计算机与信息系统学排名世界第3，统计与运筹排名第10，数学第27，电子工程排名第24。此外，卡内基梅隆的戏剧学院也享有盛誉被《好莱坞报道》评为与茱莉亚学院、纽约大学帝势艺术学院、北卡罗来纳艺术学院、加利福尼亚大学圣迭戈分校并称为全美五大最佳本科戏剧院校。截至2019年3月，该校共培养出了13个图灵奖、20个诺贝尔奖、9个奥斯卡金像奖、114个艾美奖、44个托尼奖得主。",私立,美国,2,Artificial Intelligence,是,学士,https://www.cs.cmu.edu/bs-in-artificial-intelligence/,The School of Computer Science,"Human-Computer Interaction Institute (HCII),Language Technologies Institute (LTI),Machine Learning Dept (MLD),Software and Societal Systems Department (S3D),Robotics Institute (RI)",2018年秋推出了美国第一个人工智能学士学位,https://www.cs.cmu.edu/bs-in-artificial-intelligence/admissions,Bachelor of Science in Artificial Intelligence,4years,否,360units,https://www.cs.cmu.edu/academics/undergraduate/honors-research-thesis,"Gives students the in-depth knowledge needed to transform large amounts of data into actionable decisions. The program and its curriculum focus on how complex inputs — such as vision, language and huge databases — can be used to make decisions or enhance human capabilities.","1.Understand how to distill a real-world challenge as an artificial intelligence problem, involving explicit representation and learning of symbolic and numeric models; reasoning about such models; and using such models for decision making, action selection, and interaction with humans.
2.Design, analyze, implement, and use state-of-the-art AI and machine learning techniques for dealing with real-world data, including data involving vision, language, perception, and uncertainty.
3.Master the core concepts of computer science, with emphasis on data structures, programming, computing systems, and algorithm design, performance, and correctness across a variety of metrics (e.g., time, space, parallel vs. sequential implementation, what is computable).
4.Master the fundamentals of discrete mathematics, logic, theorem proving and explanation, probability and statistics, and optimization.
5.Describe, specify, and develop large-scale, open-ended artificial intelligence systems subject constraints such as performance, available data, and need for transparency. Communicate technical material effectively to technical and non-technical audiences.
6.Work productively both individually and in teams.
7.Recognize the social impact of artificial intelligence and the underlying responsibility to consider the ethical, privacy, moral, and legal implications of artificial intelligence technologies.",否,否,是,https://www.cs.cmu.edu/bs-in-artificial-intelligence/curriculum,https://csd.cmu.edu/research/research-areas/artificial-intelligence,https://www.cs.cmu.edu/bs-in-artificial-intelligence/program-roadmap
2,卡内基梅隆大学,Carnegie Mellon University,"卡内基梅隆大学（Carnegie Mellon University），简称CMU，坐落在美国宾夕法尼亚州的匹兹堡，是一所拥有13,600名在校学生和1,423名教职及科研人员的世界顶尖学府，美国25所新常春藤盟校之一。除了匹兹堡，卡内基梅隆大学在美国硅谷以及卡塔尔设有分校，并且其在世界各地均设有合作研究机构，包括纽约、洛杉矶、华盛顿特区、中国、澳大利亚、葡萄牙、卢旺达等。该校拥有享誉全球的计算机学院和戏剧学院，其艺术学院，商学院，工程院以及公共管理学院等也都在全美名列前茅。CMU由工业家兼慈善家安德鲁·卡耐基于1900年创建，当时名为卡内基技术学校，1912年改名为卡内基梅隆大学，开始向以研究为主的美国重点大学转变。CMU位列2020U.S. News美国最佳大学排名第25名，包括最佳创新大学第7位，商科全美第5，工程院第6（本科），计算机学院第2。其量化金融项目（MSCF）常年在全美名列前3。2020QS世界大学学科排名中，其计算机与信息系统学排名世界第3，统计与运筹排名第10，数学第27，电子工程排名第24。此外，卡内基梅隆的戏剧学院也享有盛誉被《好莱坞报道》评为与茱莉亚学院、纽约大学帝势艺术学院、北卡罗来纳艺术学院、加利福尼亚大学圣迭戈分校并称为全美五大最佳本科戏剧院校。截至2019年3月，该校共培养出了13个图灵奖、20个诺贝尔奖、9个奥斯卡金像奖、114个艾美奖、45个托尼奖得主。",私立,美国,2,Artificial Intelligence and Innovation,是,专业型硕士,https://msaii.cs.cmu.edu/program-overview,The School of Computer Science-Language Technologies Institute (LTI),"Computer Science Department(CSD).Machine Learning Dept (MLD),Software and Societal Systems Department (S3D)",世界上第一个将人工智能与创新结合的硕士项目。,https://msaii.cs.cmu.edu/how-apply,Master of Science in Artificial Intelligence and Innovation,2years,否,195units,,"To prepare students to develop innovative AI applications in industry through the use of deep AI implementation skills, perception of market gaps of AI usage, the ability to persuade sponsors that a proposed AI system is worth supporting.","1.Software implementation skills
2.Facility with the techniques of AI
3.Strong AI system development capability
4.Understanding of the legal and social issues raised by AI5Ability to work in teams
5.Experience in a realistic industrial setting
6.Appreciation for the innovation and entrepreneurship processes
7.Soft skills development, including speaking and presentation skills
8Hands-on implementation of a large-scale AI system
2.Facility with the techniques of AI
3.Strong AI system development capability
4.Understanding of the legal and social issues raised by AI
5.Ability to work in teams
6.Experience in a realistic industrial setting
7.Appreciation for the innovation and entrepreneurship processes
8.Soft skills development, including speaking and presentation skills
9.Hands-on implementation of a large-scale AI system",是,是,否,https://www.eecs.mit.edu/academics/undergraduate-programs/curriculum/6-4-artificial-intelligence-and-decision-making/,https://msaii.cs.cmu.edu/directory/all/154/1,https://msaii.cs.cmu.edu/sites/default/files/Handbook-MSAII-2022-2023.pdf
3,卡内基梅隆大学,Carnegie Mellon University,"卡内基梅隆大学（Carnegie Mellon University），简称CMU，坐落在美国宾夕法尼亚州的匹兹堡，是一所拥有13,600名在校学生和1,423名教职及科研人员的世界顶尖学府，美国25所新常春藤盟校之一。除了匹兹堡，卡内基梅隆大学在美国硅谷以及卡塔尔设有分校，并且其在世界各地均设有合作研究机构，包括纽约、洛杉矶、华盛顿特区、中国、澳大利亚、葡萄牙、卢旺达等。该校拥有享誉全球的计算机学院和戏剧学院，其艺术学院，商学院，工程院以及公共管理学院等也都在全美名列前茅。CMU由工业家兼慈善家安德鲁·卡耐基于1900年创建，当时名为卡内基技术学校，1912年改名为卡内基梅隆大学，开始向以研究为主的美国重点大学转变。CMU位列2020U.S. News美国最佳大学排名第25名，包括最佳创新大学第7位，商科全美第5，工程院第6（本科），计算机学院第2。其量化金融项目（MSCF）常年在全美名列前3。2020QS世界大学学科排名中，其计算机与信息系统学排名世界第3，统计与运筹排名第10，数学第27，电子工程排名第24。此外，卡内基梅隆的戏剧学院也享有盛誉被《好莱坞报道》评为与茱莉亚学院、纽约大学帝势艺术学院、北卡罗来纳艺术学院、加利福尼亚大学圣迭戈分校并称为全美五大最佳本科戏剧院校。截至2019年3月，该校共培养出了13个图灵奖、20个诺贝尔奖、9个奥斯卡金像奖、114个艾美奖、46个托尼奖得主。",私立,美国,2,Artificial Intelligence Engineering,是,专业型硕士,https://www.meche.engineering.cmu.edu/education/graduate-programs/masters/masters-artificial-intelligence-engineering.html,College of Engineering,The Department of Mechanical Engineering,,https://www.meche.engineering.cmu.edu/education/graduate-programs/admission/index.html,"Master of Science in Artificial Intelligence Engineering - Mechanical Engineering
",3semesters,否,120units,,"teach students how to simultaneously design a system’s functionality and supporting AI mechanisms, including both its AI algorithms and the platform on which the AI runs, to produce systems that are more adaptable, resilient, and trustworthy. The program is three semesters long","1.Apply deeper knowledge of AI methods, systems, tool chains, and cross-cutting issues including security, privacy and other ethical and societal challenges
2.Identify the engineering constraints that AI-orchestrated systems must operate within
3.Solve practical problems using AI methods
4.Adapt to the latest AI-enabled tools and learn how to work with and “advise” machines
5.Demonstrate graduate-level domain knowledge in mechanical engineering",是,否,否,https://www.meche.engineering.cmu.edu/education/graduate-programs/masters/masters-artificial-intelligence-engineering.html,https://www.meche.engineering.cmu.edu/directory/index.html,https://issuu.com/cmuengineering/docs/mechanical_engineering_handbook_ms_2023-24?fr=xKAE9_zU1NQ
4,麻省理工学院,Massachusetts Institute of Technology,麻省理工学院（Massachusetts Institute of Technology），简称“麻省理工”（MIT），位于美国马萨诸塞州波士顿都市区剑桥市，主校区依查尔斯河而建，是世界著名私立研究型大学。麻省理工学院创立于1861年，早期侧重应用科学及工程学，在第二次世界大战后，麻省理工学院倚靠美国国防科技的研发需要而迅速崛起。在二战和冷战期间，麻省理工学院的研究人员对计算机、雷达以及惯性导航系统等科技发展作出了重要贡献。麻省理工学院素以顶尖的工程学和计算机科学而著名，拥有麻省理工人工智能实验室（MIT CSAIL）、林肯实验室（MIT Lincoln Lab）和麻省理工学院媒体实验室（MIT Media Lab），其研究人员发明了万维网、GNU系统、Emacs编辑器、RSA算法等等。 该校的计算机工程、电机工程等诸多工程学领域在2019-20年世界大学学术排名中位列世界前五，在2018-19年US News美国研究生院排名中位列工程学第一、计算机科学第一，与斯坦福大学、加州大学伯克利分校一同被称为工程科技界的学术领袖。 截止至2019年10月，麻省理工学院的校友、教职工及研究人员中，共产生了97位诺贝尔奖得主（世界第五）、8位菲尔兹奖得主（世界第八）以及26位图灵奖得主（世界第二）。麻省理工学院位列2020-21年度QS世界大学排名第一 、软科世界大学学术排名第四、THE世界大学排名第五。同时列2020U.S. News世界大学排名第二，2020THE世界大学声誉排名世界第二。,私立,美国,1,Artificial Intelligence and Decision Making,是,学士,https://catalog.mit.edu/degree-charts/artifical-intelligence-decision-making-course-6-4/,School of Engineering,"Department of Electrical Engineering and Computer Science (EECS), Computer Science and Artificial Intelligence Lab (CSAIL), the Laboratory for Information and Decision Systems (LIDS), the Microsystems and Technology Laboratories (MTL) and the Research Laboratory of Electronics (RLE)",,https://mitadmissions.org/apply/,Bachelor of Science in Artificial Intelligence and Decision Making,4years,否,183-192units ,,Our educational mission is to provide students with the strong mathematical and algorithmic foundations needed to build robust systems that can extrapolate from data to insights and decisions.,Engineering Ethos.Leadership.Versatility.Engagement.ABET Accreditation,否,是,是,https://www.eecs.mit.edu/academics/undergraduate-programs/curriculum/6-4-artificial-intelligence-and-decision-making/,https://www.eecs.mit.edu/role/faculty-aid/?fwp_role=faculty-aid,
5,麻省理工学院,Massachusetts Institute of Technology,麻省理工学院（Massachusetts Institute of Technology），简称“麻省理工”（MIT），位于美国马萨诸塞州波士顿都市区剑桥市，主校区依查尔斯河而建，是世界著名私立研究型大学。麻省理工学院创立于1861年，早期侧重应用科学及工程学，在第二次世界大战后，麻省理工学院倚靠美国国防科技的研发需要而迅速崛起。在二战和冷战期间，麻省理工学院的研究人员对计算机、雷达以及惯性导航系统等科技发展作出了重要贡献。麻省理工学院素以顶尖的工程学和计算机科学而著名，拥有麻省理工人工智能实验室（MIT CSAIL）、林肯实验室（MIT Lincoln Lab）和麻省理工学院媒体实验室（MIT Media Lab），其研究人员发明了万维网、GNU系统、Emacs编辑器、RSA算法等等。 该校的计算机工程、电机工程等诸多工程学领域在2019-20年世界大学学术排名中位列世界前五，在2018-19年US News美国研究生院排名中位列工程学第一、计算机科学第一，与斯坦福大学、加州大学伯克利分校一同被称为工程科技界的学术领袖。 截止至2019年10月，麻省理工学院的校友、教职工及研究人员中，共产生了97位诺贝尔奖得主（世界第五）、8位菲尔兹奖得主（世界第八）以及26位图灵奖得主（世界第二）。麻省理工学院位列2020-21年度QS世界大学排名第一 、软科世界大学学术排名第四、THE世界大学排名第五。同时列2020U.S. News世界大学排名第二，2020THE世界大学声誉排名世界第二。,私立,美国,1,Artificial Intelligence and Decision Making,是,学术型硕士,https://www.eecs.mit.edu/academics/undergraduate-programs/meng-program/,School of Engineering,"Department of Electrical Engineering and Computer Science (EECS), Computer Science and Artificial Intelligence Lab (CSAIL), the Laboratory for Information and Decision Systems (LIDS), the Microsystems and Technology Laboratories (MTL) and the Research Laboratory of Electronics (RLE)",ABET Accredited,https://www.eecs.mit.edu/academics/undergraduate-programs/meng-program/application-acceptance/,Master of Engineering in Artificial Intelligence and Decision Making,2-3 years,是,90 units ,http://student.mit.edu/catalog/search.cgi?search=6.THM,Our educational mission is to provide students with the strong mathematical and algorithmic foundations needed to build robust systems that can extrapolate from data to insights and decisions.,Engineering Ethos.Leadership.Versatility.Engagement,是,是,否,https://www.eecs.mit.edu/academics/undergraduate-programs/meng-program/requirements/,https://www.eecs.mit.edu/role/faculty-aid/?fwp_role=faculty-aid,
6,斯坦福大学,Stanford University,斯坦福大学（Stanford University），全名小利兰·斯坦福大学（Leland Stanford Junior University），简称“斯坦福”，位于美国加州旧金山湾区南部帕罗奥多市境内，临近高科技园区硅谷（Silicon Valley），是世界著名私立研究型大学。斯坦福大学于1885年成立，1891年开始正式招生，占地约33平方公里（8180英亩），是美国占地面积第六大的大学。斯坦福大学与旧金山北湾的加州大学伯克利分校共同构成了美国西部的学术中心，并负责运行管理SLAC国家加速器实验室、胡佛研究所等机构。据统计，截至2020年3月，共有83位斯坦福大学的校友、教授及研究人员曾获得诺贝尔奖（世界第七）、28位曾获得图灵奖（世界第一）、8位曾获得过菲尔兹奖（世界第八）。 2019-20年度位列U.S. News世界大学排名第3、THE世界大学声誉排名第3、自然指数排名第4 。2020-21年度位列QS世界大学排名第2、软科世界大学学术排名第2 、THE世界大学排名第4、莫斯科国际大学排名第7，斯坦福大学为硅谷的形成和崛起奠定了坚实的基础，培养了众多高科技公司的领导者，其中包括惠普、谷歌、雅虎、耐克、罗技、Snapchat、美国艺电公司、太阳微、NVIDIA、思科及LinkedIn等公司的创办人。 此外，斯坦福的校友涵盖30名富豪企业家及17名NASA太空员，亦为培养最多美国国会成员的高等院校之一。根据《福布斯》2010年盘点的亿万富豪最多的大学，斯坦福大学名列第二，亿万富豪数量达28位、仅次于哈佛大学。,私立,美国,4,Computer Science-Artificial Intelligence (AI),"否,作为研究方向",学士,https://www.cs.stanford.edu/academics/academics-bachelors-program,School of Engineering,Computer Science Department(CSD),,https://admission.stanford.edu/apply/,Bachelor of Science,4years,否,96units,https://www.cs.stanford.edu/bs-requirements-senior-project,to prepare students for a rapidly changing world.,/,否,否,是,https://www.cs.stanford.edu/courses-overview,https://www.cs.stanford.edu/people-cs/faculty-research/artificial-intelligence,https://ughb.stanford.edu/majors-minors/computer-science-program
7,斯坦福大学,Stanford University,斯坦福大学（Stanford University），全名小利兰·斯坦福大学（Leland Stanford Junior University），简称“斯坦福”，位于美国加州旧金山湾区南部帕罗奥多市境内，临近高科技园区硅谷（Silicon Valley），是世界著名私立研究型大学。斯坦福大学于1885年成立，1891年开始正式招生，占地约33平方公里（8180英亩），是美国占地面积第六大的大学。斯坦福大学与旧金山北湾的加州大学伯克利分校共同构成了美国西部的学术中心，并负责运行管理SLAC国家加速器实验室、胡佛研究所等机构。据统计，截至2020年3月，共有83位斯坦福大学的校友、教授及研究人员曾获得诺贝尔奖（世界第七）、28位曾获得图灵奖（世界第一）、8位曾获得过菲尔兹奖（世界第八）。 2019-20年度位列U.S. News世界大学排名第3、THE世界大学声誉排名第3、自然指数排名第4 。2020-21年度位列QS世界大学排名第2、软科世界大学学术排名第2 、THE世界大学排名第4、莫斯科国际大学排名第7，斯坦福大学为硅谷的形成和崛起奠定了坚实的基础，培养了众多高科技公司的领导者，其中包括惠普、谷歌、雅虎、耐克、罗技、Snapchat、美国艺电公司、太阳微、NVIDIA、思科及LinkedIn等公司的创办人。 此外，斯坦福的校友涵盖30名富豪企业家及17名NASA太空员，亦为培养最多美国国会成员的高等院校之一。根据《福布斯》2010年盘点的亿万富豪最多的大学，斯坦福大学名列第二，亿万富豪数量达29位、仅次于哈佛大学。,私立,美国,4,Computer Science-Artificial Intelligence (AI),"否,作为研究方向",专业型硕士,https://www.cs.stanford.edu/masters-program-overview,School of Engineering,,,https://www.cs.stanford.edu/admissions/masters-admissions,Master of Science in Computer Science,1.5years,否,45units,,to prepare students for a rapidly changing world.,/,否,否,是,https://drive.google.com/file/d/19F3s-E44_F5ww-7x43_lN9LmRNJKB1GM/view?usp=sharing,https://www.cs.stanford.edu/people-cs/faculty-research/artificial-intelligence,
8,加州大学伯克利分校,University of California，Berkeley,加利福尼亚大学（University of California），简称加州大学，是位于美国加利福尼亚州的一个由10所公立大学组成的大学行政系统，是世界上最具影响力的公立大学系统，被誉为“公立高等教育的典范”。加州大学起源于1853年建立在奥克兰的加利福尼亚学院（College of California），1868年3月正式更名为“加州大学”。1873年，学校迁入新址，为了纪念18世纪最伟大的哲学家之一乔治·贝克莱，新的大学城被命名为“伯克利市”，此后逐渐在洛杉矶等地开设分校区。1952年起，“加州大学”作为一个行政系统逐渐与伯克利加州大学分离。与此同时，加州各地的分校区也逐渐升格为与伯克利平级的、独立的大学。如今，加州大学已发展成一个拥有10所公立大学并对世界发展影响深远的大学系统。这些校区包括加州大学伯克利分校（UC Berkeley）、加州大学洛杉矶分校（UCLA）、加州大学圣地亚哥分校（UCSD）、加州大学旧金山分校（UCSF）、加州大学圣塔芭芭拉分校（UCSB）、加州大学尔湾分校（UCI）、加州大学戴维斯分校（UCD）、加州大学圣克鲁兹分校（UCSC）、加州大学河滨分校（UCR）和加州大学美熹德分校（UCM）。（注：现今的加州大学并没有所谓的“主校区”，“分校”一词只是中文翻译误区）加州大学是世界最大的大学联邦体，其旗下大学在各项学术指标和排名中均名列前茅。这些校区互为独立又紧密联系，各自作为独立的大学而存在，共同组成了享誉全美乃至全世界的加州大学。,公立,美国,3,Computer Science-Artificial Intelligence (AI),"否,作为研究方向",学术型硕士,https://eecs.berkeley.edu/academics/graduate/research-programs/,College of Engineering,Department of Electrical Engineering & Computer Sciences，The Berkeley Artificial Intelligence Research (BAIR) Lab,,https://eecs.berkeley.edu/academics/graduate/research-programs/admissions/,Master of Science in Computer Science,只获得硕士学位2years；5-6年可获得硕士、博士学位,可选,2年制学位-24units,https://eecs.berkeley.edu/book/ms/thesis-report/,The Master of Science (MS) program is a very small research program for exceptional applicants with research experience. Both (M.S./Ph.D.)ull program for those who know they would like to pursue a Ph.D at Berkeley.,Leads to career in industrial R&D or Ph.D/Research preparation for the PhD.,否,否,是,https://www2.eecs.berkeley.edu/Courses/CS/,https://www2.eecs.berkeley.edu/Research/Areas/AI/,https://docs.google.com/document/d/1x_H1yoRZFbRiyr76N6MMqUSxngfl9alKt3FnP2tiUhw/edit#heading=h.2vgusr5pkrih
9,加州大学伯克利分校,University of California，Berkeley,加利福尼亚大学（University of California），简称加州大学，是位于美国加利福尼亚州的一个由10所公立大学组成的大学行政系统，是世界上最具影响力的公立大学系统，被誉为“公立高等教育的典范”。加州大学起源于1853年建立在奥克兰的加利福尼亚学院（College of California），1868年3月正式更名为“加州大学”。1873年，学校迁入新址，为了纪念18世纪最伟大的哲学家之一乔治·贝克莱，新的大学城被命名为“伯克利市”，此后逐渐在洛杉矶等地开设分校区。1952年起，“加州大学”作为一个行政系统逐渐与伯克利加州大学分离。与此同时，加州各地的分校区也逐渐升格为与伯克利平级的、独立的大学。如今，加州大学已发展成一个拥有11所公立大学并对世界发展影响深远的大学系统。这些校区包括加州大学伯克利分校（UC Berkeley）、加州大学洛杉矶分校（UCLA）、加州大学圣地亚哥分校（UCSD）、加州大学旧金山分校（UCSF）、加州大学圣塔芭芭拉分校（UCSB）、加州大学尔湾分校（UCI）、加州大学戴维斯分校（UCD）、加州大学圣克鲁兹分校（UCSC）、加州大学河滨分校（UCR）和加州大学美熹德分校（UCM）。（注：现今的加州大学并没有所谓的“主校区”，“分校”一词只是中文翻译误区）加州大学是世界最大的大学联邦体，其旗下大学在各项学术指标和排名中均名列前茅。这些校区互为独立又紧密联系，各自作为独立的大学而存在，共同组成了享誉全美乃至全世界的加州大学。,公立,美国,3,Electrical Engineering and Computer Sciences-Computer Vision and Artificial Intelligence (CVAI),"否,作为研究方向",学术型硕士,https://eecs.berkeley.edu/academics/graduate/research-programs/,College of Engineering,Department of Electrical Engineering & Computer Sciences，The Berkeley Artificial Intelligence Research (BAIR) Lab,,https://eecs.berkeley.edu/academics/graduate/research-programs/admissions/,Master of Science in Electrical Engineering and Computer Sciences,只获得硕士学位2years；5-7年可获得硕士、博士学位,可选,2年制学位-24units,https://eecs.berkeley.edu/book/ms/thesis-report/,The Master of Science (MS) program is a very small research program for exceptional applicants with research experience. Both (M.S./Ph.D.)ull program for those who know they would like to pursue a Ph.D at Berkeley.,Leads to career in industrial R&D or Ph.D/Research preparation for the PhD.,否,否,是,https://www2.eecs.berkeley.edu/Courses/EE/,https://www3.eecs.berkeley.edu/Research/Areas/AI/,https://docs.google.com/document/d/1x_H1yoRZFbRiyr76N6MMqUSxngfl9alKt3FnP2tiUhw/edit#heading=h.2vgusr5pkrih
10,加州大学伯克利分校,University of California，Berkeley,加利福尼亚大学（University of California），简称加州大学，是位于美国加利福尼亚州的一个由10所公立大学组成的大学行政系统，是世界上最具影响力的公立大学系统，被誉为“公立高等教育的典范”。加州大学起源于1853年建立在奥克兰的加利福尼亚学院（College of California），1868年3月正式更名为“加州大学”。1873年，学校迁入新址，为了纪念18世纪最伟大的哲学家之一乔治·贝克莱，新的大学城被命名为“伯克利市”，此后逐渐在洛杉矶等地开设分校区。1952年起，“加州大学”作为一个行政系统逐渐与伯克利加州大学分离。与此同时，加州各地的分校区也逐渐升格为与伯克利平级的、独立的大学。如今，加州大学已发展成一个拥有10所公立大学并对世界发展影响深远的大学系统。这些校区包括加州大学伯克利分校（UC Berkeley）、加州大学洛杉矶分校（UCLA）、加州大学圣地亚哥分校（UCSD）、加州大学旧金山分校（UCSF）、加州大学圣塔芭芭拉分校（UCSB）、加州大学尔湾分校（UCI）、加州大学戴维斯分校（UCD）、加州大学圣克鲁兹分校（UCSC）、加州大学河滨分校（UCR）和加州大学美熹德分校（UCM）。（注：现今的加州大学并没有所谓的“主校区”，“分校”一词只是中文翻译误区）加州大学是世界最大的大学联邦体，其旗下大学在各项学术指标和排名中均名列前茅。这些校区互为独立又紧密联系，各自作为独立的大学而存在，共同组成了享誉全美乃至全世界的加州大学。,公立,美国,3,Electrical Engineering and Computer Sciences-Computer Vision and Artificial Intelligence (CVAI),"否,作为研究方向",博士,https://eecs.berkeley.edu/academics/graduate/research-programs/,College of Engineering,Department of Electrical Engineering & Computer Sciences，The Berkeley Artificial Intelligence Research (BAIR) Lab,,https://eecs.berkeley.edu/academics/graduate/research-programs/admissions/,Doctor of Philosophy in Electrical Engineering and Computer Sciences,"5-6 years (从学士学位开始),  3-5 years (从硕士学位开始)",是,24 semester units,https://eecs.berkeley.edu/book/phd/quals/thesis-proposal-defense/,A Ph.D. in EECS combines coursework and original research with exceptional faculty mentoring to  prepare for a career in academia or industry.,Research + teaching experience,是,是,是,https://eecs.berkeley.edu/book/phd/coursework/,https://www2.eecs.berkeley.edu/Research/Areas/AI/,https://docs.google.com/document/d/1x_H1yoRZFbRiyr76N6MMqUSxngfl9alKt3FnP2tiUhw/edit#heading=h.2vgusr5pkrih
11,哈佛大学,Harvard University,哈佛大学（Harvard University），简称“哈佛”，享誉世界的私立研究型大学，著名的常春藤盟校成员，坐落于美国马萨诸塞州波士顿都市区剑桥市。哈佛大学是美国本土历史最悠久的高等学府，建立于1636年，最早由马萨诸塞州殖民地立法机关创建，初名“新市民学院”。为了纪念在成立初期给予学院慷慨支持的约翰·哈佛牧师，学校于1639年3月更名为“哈佛学院（Harvard College）”，而1780年哈佛学院正式改称“哈佛大学（Harvard University）”。 哈佛大学由十所学院以及一个高等研究所构成，坐拥世界上规模最大的大学图书馆系统，2018学年注册本科生6699余人、硕士及博士研究生13120余人。哈佛大学在文学、医学、法学、商学等多个领域拥有崇高的学术地位及广泛的影响力，被公认为是当今世界最顶尖的高等教育及研究机构之一。 同时，该校还负责管理运行哈佛-史密松森天体物理中心、麻省总医院、波士顿儿童医院等机构。截至2019年10月，哈佛大学共培养了包括富兰克林·罗斯福、贝拉克·奥巴马在内的8位美利坚合众国总统，而哈佛的校友、教授及研究人员中共产生了160位诺贝尔奖得主（世界第一）、18位菲尔兹奖得主（世界第一）、14位图灵奖得主（世界第四）。 2019-20年，哈佛大学位列U.S. News世界大学排名世界第一、软科世界大学学术排名世界第一、QS世界大学排名世界第三、THE世界大学排名世界第七；THE世界大学声誉排名世界第一。2020软科世界大学学术排名世界第一、莫斯科国际大学排名世界第一。,私立,美国,5,Computer Science-Artificial Intelligence,"否,作为研究方向",博士,https://seas.harvard.edu/computer-science/graduate-program,Harvard John A.PaulsonSchool of Engineeringand Applied Sciences,"Harvard Kenneth C. Griffin Graduate School of Arts and Sciences,Center for Research on Computation and Society, Data Science Initiative, Berkman Klein Center for Internet and Society.",,https://gsas.harvard.edu/apply,Doctor of Philosophy  in Computer Science,5-6 years,否,32units,https://registrar.fas.harvard.edu/submit-your-dissertation,learn both the fundamentals of computation and computation’s interaction with the world,Examples of projects current and past students have worked on include leveraging machine learning to solve real-world sequential decision-making problems and using artificial intelligence to help conservation and anti-poaching efforts around the world.,否,是,否,https://seas.harvard.edu/computer-science/graduate-program/general-requirements/cs-phd-course-requirements,https://seas.harvard.edu/computer-science/people?research[251]=251,https://handbook.college.harvard.edu/sites/projects.iq.harvard.edu/files/collegehandbook/files/fields_of_concentration_8.31.23_final_with_additional_edits_unsecured_.pdf
12,佐治亚理工学院,Georgia Institute of Technology,佐治亚理工学院（Georgia Institute of Technology），简称Gatech，是1885年建校于美国佐治亚州首府亚特兰大的公立研究型大学，美国大学协会成员，被誉为“公立常春藤”，埃默里大学的姐妹校。佐治亚理工学院与麻省理工学院（MIT）、加州理工学院（Caltech）并称为美国三大理工学院，是美国南部最好的理工类院校之一，在法国梅斯及中国深圳设有两个海外校区。,公立,美国,13,Computer Science-Computing and Intelligence,"否,作为研究方向",学士,https://catalog.gatech.edu/programs/computer-science-bs/#text,College of Computing,School of Computer Science,"Our program is based on a unique concept, Threads™ , a significant College of Computing innovation in undergraduate CS education. ",https://catalog.gatech.edu/admissions/ugrad/first-year/,Bachelor of Science in Computer Science - Thread: Devices & Intelligence,4years,否,126 credits,,"Reasoning with uncertainty
Reasoning on action and change
Heuristic methods for solving problems that are difficult or impractical to solve with other methods
Techniques for handling high-dimensional spaces
Modeling Static vs Dynamic worlds","Able to implement a variety of pattern recognition and control algorithms, and understanding the applicability of each
Able to build fast approximation algorithms when necessary for dealing with otherwise impractical problems, such as those dealing with streams of high dimensional data or large search spaces
Able to develop autonomous systems in a variety of domains",否,是,是,https://www.cc.gatech.edu/academics/threads/intelligence,https://www.cc.gatech.edu/people/faculty?field_person_school_target_id%5B204%5D=204,
13,佐治亚理工学院,Georgia Institute of Technology,佐治亚理工学院（Georgia Institute of Technology），简称Gatech，是1885年建校于美国佐治亚州首府亚特兰大的公立研究型大学，美国大学协会成员，被誉为“公立常春藤”，埃默里大学的姐妹校。佐治亚理工学院与麻省理工学院（MIT）、加州理工学院（Caltech）并称为美国三大理工学院，是美国南部最好的理工类院校之一，在法国梅斯及中国深圳设有两个海外校区。,公立,美国,13,Computer Science-Interactive Intelligence/Machine Learning,"否,作为研究方向",专业型硕士,https://catalog.gatech.edu/programs/computer-science-ms/,College of Computing,"School of Computer Science, Cybersecurity and Privacy, Interactive Computing, Computing Instruction, and Computational Science and Engineering.",,https://grad.gatech.edu/admissions,Master of Science in Computer Science,1.5years,否,30 units,https://grad.gatech.edu/theses-dissertations,"establish an educational environment that will strengthen students’ personal and professional development, to encourage students and faculty to pursue the discovery and generation of new knowledge through research, to investigate ways of applying such knowledge for the benefit of society and humanity, and to foster the development of new tools, objects, and ideas.",,是,是,是,https://www.cc.gatech.edu/ms-computer-science-specializations,https://www.cc.gatech.edu/people/faculty?field_person_school_target_id%5B204%5D=205,https://www.cc.gatech.edu/sites/default/files/documents/2024/MSCS%20Handbook%5B8%5D.pdf
14,佐治亚理工学院,Georgia Institute of Technology,佐治亚理工学院（Georgia Institute of Technology），简称Gatech，是1885年建校于美国佐治亚州首府亚特兰大的公立研究型大学，美国大学协会成员，被誉为“公立常春藤”，埃默里大学的姐妹校。佐治亚理工学院与麻省理工学院（MIT）、加州理工学院（Caltech）并称为美国三大理工学院，是美国南部最好的理工类院校之一，在法国梅斯及中国深圳设有两个海外校区。,公立,美国,13,Machine Learning,"否,作为研究方向",博士,https://catalog.gatech.edu/programs/machine-learning-phd/#overviewtext,College of Computing,"Schools of Computational Science and Engineering, Computer Science, and Interactive Computing in the College of Computing; the Schools of Aerospace Engineering, Chemical and Biomolecular Engineering, Industrial and Systems Engineering, Electrical and Computer Engineering, and Biomedical Engineering in the College of Engineering; and the School of Mathematics in the College of Science.",,https://grad.gatech.edu/admissions,Ph.D. in Machine Learning,7years,否,37hours,https://ml.gatech.edu/content/curriculum-phd-dissertation,"Create students that are able to advance the state of knowledge and practice in machine learning through innovative research contributions.
Create students who are able to integrate and apply principles from computing, statistics, optimization, engineering, mathematics and science to innovate, and create machine learning models and apply them to solve important real-world data intensive problems.
Create students who are able to participate in multidisciplinary teams that include individuals whose primary background is in statistics, optimization, engineering, mathematics and science.
Provide a high quality education that prepares individuals for careers in industry, government (e.g., national laboratories), and academia, both in terms of knowledge, computational (e.g., software development) skills, and mathematical modeling skills.
Foster multidisciplinary collaboration among researchers and educators in areas such as computer science, statistics, optimization, engineering, social science, and computational biology.
Foster economic development in the state of Georgia.
Advance Georgia Tech’s position of academic leadership by attracting high quality students who would not otherwise apply to Tech for graduate study.","•    Students will develop a solid understanding of fundamental principles across a range of core areas in the machine learning discipline.
•    Students will develop a deep understanding and set of skills and expertise in a specific theoretical aspect or application area of the machine learning discipline.
•    The students will be able to apply and integrate the knowledge and skills they have developed and demonstrate their expertise and proficiency in an application area of practical importance.
•    Students will be able to engage in multidisciplinary activities by being able to communicate complex ideas in their area of expertise to individuals in other fields, be able to understand complex ideas and concepts from other disciplines, and be able to incorporate these concepts into their own work.",否,否,是,https://catalog.gatech.edu/programs/machine-learning-phd/#requirementstext,https://public.tableau.com/views/MachineLearningCenteratGeorgiaTechMLGT/Dashboard1?%3AshowVizHome=no,https://www.dropbox.com/s/jhyw1oledevm3wa/Machine%20Learning%20PhD%20Handbook%20(Current).pdf?e=1&dl=0
15,伊利诺伊大学厄巴纳香槟分校,University of Illinois at Urbana-Champaign,伊利诺伊大学（University of Illinois），简称UI或U of I，创建于1867年，是美国最具影响力的公立大学系统之一，拥有“公立常春藤”的美誉，在全世界享有盛名。其三所分校分别位于伊利诺伊州的大学城厄巴纳-香槟、第一大城市芝加哥以及州府斯普林菲尔德。伊利诺伊大学厄巴纳-香槟分校（UIUC）是美国顶尖的综合研究型大学，是美国十大联盟创始成员和美国大学协会成员，其工科综合实力稳居全美前五，在理学和社会科学领域亦是世界一流水平，在此学习和工作过的校友中有30位获得诺贝尔奖，2020THE世界大学排名第48位，2019软科世界大学学术排名第38位。伊利诺伊大学芝加哥分校（UIC）是芝加哥地区最大的公立研究型大学，美国一级国家级大学，在法学、教育学、新闻传播学、公共事务、以及医学和健康科学领域处于世界领先水平，拥有全美最大的医学院。伊利诺伊大学斯普林菲尔德分校（UIS）是一所文理学院，在美国中西部公立大学中名列前茅。伊利诺伊大学与中国有着特殊的关系，早在1906年，时任校长爱德蒙·詹姆斯致信美国总统西奥多·罗斯福，建议将庚子赔款用于发展中国的教育事业，后来发展为庚子赔款奖学金，诸多的中国学生藉此得以留美深造。在1911-1920年间，伊利诺伊大学收留和培养了多达三成的留美中国学生，是对中国学生最友好的美国大学之一。该校还是美国最多元化、国际化的大学之一，其中UIUC的国际学生人数常年位于全美大学第三位，位列美国公立大学榜首。,公立,美国,14,"Computer engineering-Artificial intelligence, robotics, and cybernetics","否,作为研究方向",学士,https://ece.illinois.edu/academics/ugrad/curriculum,The Grainger College of Engineering,Department of Electrical & Computer Engineering,ABET Accredited,https://ece.illinois.edu/admissions/undergraduate,Bachelor of science in computer engineering,4 years,否,128 hours,,"Pursue a diverse range of careers as engineers, consultants, and entrepreneurs.
Continue their education in leading graduate programs in engineering and interdisciplinary areas to emerge as researchers, experts, and educators.
Learn and create new knowledge in ever-changing environments of the 21st century, and communicate their work and ideas to colleagues and the public at large.
Practice and inspire high ethical and technical standards, and lead their professional disciplines, organizations, and communities globally.","Principles: ability to identify, formulate, and solve complex engineering problems by applying principles of engineering, science, and mathematics
Design: ability to apply engineering design to produce solutions that meet specified needs with consideration of public health, safety, and welfare, as well as global, cultural, social, environmental, and economic factors
Communication: ability to communicate effectively with a range of audiences
Professionalism: ability to recognize ethical and professional responsibilities in engineering situations and make informed judgments, which must consider the impact of engineering solutions in global, economic, environmental, and societal contexts
Teamwork: ability to function effectively on a team whose members together provide leadership, create a collaborative and inclusive environment, establish goals, plan tasks, and meet objectives
Analysis: ability to develop and conduct appropriate experimentation, analyze and interpret data, and use engineering judgment to draw conclusions
Learning: ability to acquire and apply new knowledge as needed, using appropriate learning strategies
University of Illinois Urbana Champaign
Get In Touch Make a Gift",否,否 ,是,https://ece.illinois.edu/academics/ugrad/curriculum/ce,https://ece.illinois.edu/academics/ugrad/subdisciplines/robotics,https://ece.illinois.edu/academics/ugrad/curriculum/ce
16,伊利诺伊大学厄巴纳香槟分校,University of Illinois at Urbana-Champaign,伊利诺伊大学（University of Illinois），简称UI或U of I，创建于1867年，是美国最具影响力的公立大学系统之一，拥有“公立常春藤”的美誉，在全世界享有盛名。其三所分校分别位于伊利诺伊州的大学城厄巴纳-香槟、第一大城市芝加哥以及州府斯普林菲尔德。伊利诺伊大学厄巴纳-香槟分校（UIUC）是美国顶尖的综合研究型大学，是美国十大联盟创始成员和美国大学协会成员，其工科综合实力稳居全美前五，在理学和社会科学领域亦是世界一流水平，在此学习和工作过的校友中有30位获得诺贝尔奖，2020THE世界大学排名第48位，2019软科世界大学学术排名第38位。伊利诺伊大学芝加哥分校（UIC）是芝加哥地区最大的公立研究型大学，美国一级国家级大学，在法学、教育学、新闻传播学、公共事务、以及医学和健康科学领域处于世界领先水平，拥有全美最大的医学院。伊利诺伊大学斯普林菲尔德分校（UIS）是一所文理学院，在美国中西部公立大学中名列前茅。伊利诺伊大学与中国有着特殊的关系，早在1906年，时任校长爱德蒙·詹姆斯致信美国总统西奥多·罗斯福，建议将庚子赔款用于发展中国的教育事业，后来发展为庚子赔款奖学金，诸多的中国学生藉此得以留美深造。在1911-1920年间，伊利诺伊大学收留和培养了多达三成的留美中国学生，是对中国学生最友好的美国大学之一。该校还是美国最多元化、国际化的大学之一，其中UIUC的国际学生人数常年位于全美大学第三位，位列美国公立大学榜首。,公立,美国,14,"Computer Science-Computer Vision, Robotics and AI","否,作为研究方向",学术型硕士,https://cs.illinois.edu/academics/graduate/ms-program,The Grainger College of Engineering,Department of Electrical & Computer Engineering,,https://ece.illinois.edu/admissions/graduate,Master of Science in Computer Science,2years,否,32 credit hours,https://cs.illinois.edu/academics/graduate/phd-program/phd-ms-thesis-format-review-guidelines,Our master of science degree allows students to truly master concepts that will allow them to become visionaries in fields related to electrical and computer engineering.,"Demonstrate in-depth knowledge of a particular subject area and broad knowledge of other areas in Computer Science.
Analyze, design, and construct Computer Science-based solutions for current technological challenges.
Plan and conduct original research that addresses questions of significance in a particular subject area in Computer Science.
Analyze and be able to articulate the scientific advances and limitations of results described in the research literature.
Demonstrate the ability to effectively communicate research proposals and results.
Demonstrate an understanding of and ability to follow ethical standards in research and professional service.",否,否,否,https://cs.illinois.edu/academics/graduate/ms-program,https://cs.illinois.edu/about/people/all-faculty,https://ece.illinois.edu/academics/grad/msphd-manual
17,伊利诺伊大学厄巴纳香槟分校,University of Illinois at Urbana-Champaign,伊利诺伊大学（University of Illinois），简称UI或U of I，创建于1867年，是美国最具影响力的公立大学系统之一，拥有“公立常春藤”的美誉，在全世界享有盛名。其三所分校分别位于伊利诺伊州的大学城厄巴纳-香槟、第一大城市芝加哥以及州府斯普林菲尔德。伊利诺伊大学厄巴纳-香槟分校（UIUC）是美国顶尖的综合研究型大学，是美国十大联盟创始成员和美国大学协会成员，其工科综合实力稳居全美前五，在理学和社会科学领域亦是世界一流水平，在此学习和工作过的校友中有30位获得诺贝尔奖，2020THE世界大学排名第48位，2019软科世界大学学术排名第38位。伊利诺伊大学芝加哥分校（UIC）是芝加哥地区最大的公立研究型大学，美国一级国家级大学，在法学、教育学、新闻传播学、公共事务、以及医学和健康科学领域处于世界领先水平，拥有全美最大的医学院。伊利诺伊大学斯普林菲尔德分校（UIS）是一所文理学院，在美国中西部公立大学中名列前茅。伊利诺伊大学与中国有着特殊的关系，早在1906年，时任校长爱德蒙·詹姆斯致信美国总统西奥多·罗斯福，建议将庚子赔款用于发展中国的教育事业，后来发展为庚子赔款奖学金，诸多的中国学生藉此得以留美深造。在1911-1920年间，伊利诺伊大学收留和培养了多达三成的留美中国学生，是对中国学生最友好的美国大学之一。该校还是美国最多元化、国际化的大学之一，其中UIUC的国际学生人数常年位于全美大学第三位，位列美国公立大学榜首。,公立,美国,14,"Computer Science-Computer Vision, Robotics and AI","否,作为研究方向",博士,https://ece.illinois.edu/academics/grad/msphd-manual/phd,The Grainger College of Engineering,Department of Electrical & Computer Engineering,,https://ece.illinois.edu/admissions/graduate,Doctor of Philosophy in Computer Science,5-7years,否,96 credits hours ,http://catalog.illinois.edu/graduate/engineering/computer-science-phd/#degreerequirementstext,Our Ph.D. program is designed to guide students through the process of becoming an independent researcher and educator in their field of expertise.,"Demonstrate in-depth knowledge of a particular subject area and broad knowledge of other areas in Computer Science.
Analyze and be able to articulate the scientific advances and limitations of results described in the research literature.
Plan and conduct original research that addresses questions of significance in a particular subject area in Computer Science.
Demonstrate the ability to effectively write research proposals and results.
Present research effectively through oral presentations inside the department as well as at external venues.
Demonstrate an understanding of and ability to follow ethical standards in research, teaching, and professional service.
Demonstrate the ability to teach concepts in Computer Science at the university level, including classroom management skills, techniques for effective lecturing, and methods for guiding and assessing students.",否 ,否,否,https://ece.illinois.edu/academics/grad/msphd-manual/phd,https://cs.illinois.edu/about/people/all-faculty,https://ece.illinois.edu/academics/grad/msphd-manual
18,普林斯顿大学,Princeton University,普林斯顿大学（Princeton University），简称“普林斯顿”，是世界著名私立研究型大学，位于美国东海岸新泽西州的普林斯顿市，是美国大学协会的14个始创院校之一，也是著名的常春藤联盟成员。基督教教会曙光长老会于1746年在新泽西州伊丽莎白镇创立该校，是美国殖民时期第四所成立的高等院校，当时名为“新泽西学院（College of New Jersey）”。1747年学校迁至新泽西州，1756年迁至风景优美的普林斯顿市（位于费城和纽约之间），并在1896年正式改名为“普林斯顿大学”。截止至2019年，普林斯顿大学共培养了2位美国总统、12位美国最高法院大法官以及众多美国国会议员。 截止2020年3月，普林斯顿大学的校友、教授及研究人员中，共产生了68位诺贝尔奖获得主（世界第十）、15位世界数学最高奖菲尔兹奖得主（世界第三）、14位世界计算机最高奖图灵奖得主（世界第四）。2019-2020年，普林斯顿大学位列U.S. News美国最佳大学排名全美第一，软科世界大学学术排名世界第6、THE世界大学排名世界第6、U.S. News世界大学排名世界第8、QS世界大学排名世界第13；THE世界大学声誉排名世界第7。2020年莫斯科国际大学排名世界第25，2021年QS世界大学排名世界第12。,私立,美国,15,Computer Science-Machine Learning ,"否,作为研究方向",学士,https://ua.princeton.edu/fields-study/departmental-majors-degree-bachelor-science-engineering/computer-science-bse,The School of Engineering and Applied Science,"Department of
COMPUTER SCIENCE",,https://admission.princeton.edu/,Bachelor of Science in Engineering,4years,否,36 courses ,,"Undergraduates learn fundamental concepts of the discipline and to become proficient in the use of advanced computer systems. The plan provides opportunities for study in software systems, algorithms and complexity, machine architecture, computer graphics, programming languages, machine learning, and other core areas of computer science","Students will be able to understand, modify, debug, refactor and analyze programs in a variety of different programming languages; 
Students will be able to learn new programming languages and computational paradigms they encounter in the future;
Students will be able to read and comprehend technical literature in computer science;
Students will be able to plan and complete a one- or two-term project in an area of computer science of their choice;
Students will be able to identify, isolate and solve important technical subproblems that lead to a solution to a more significant problem;
Students will be able to present technical ideas in computer science clearly, both orally and in written form;
Students will be able to identify and assess related work in their area of study;
Students will demonstrate an ability to work independently in accomplishing all of the above goals.",是,是,是,https://engineering.princeton.edu/undergraduate-studies/first-year-advising/degree-requirements,https://aiml.cs.princeton.edu/,https://www.cs.princeton.edu/sites/default/files/cos-bse-iw-handbook_23-24.pdf
19,普林斯顿大学,Princeton University,普林斯顿大学（Princeton University），简称“普林斯顿”，是世界著名私立研究型大学，位于美国东海岸新泽西州的普林斯顿市，是美国大学协会的14个始创院校之一，也是著名的常春藤联盟成员。基督教教会曙光长老会于1746年在新泽西州伊丽莎白镇创立该校，是美国殖民时期第四所成立的高等院校，当时名为“新泽西学院（College of New Jersey）”。1747年学校迁至新泽西州，1756年迁至风景优美的普林斯顿市（位于费城和纽约之间），并在1896年正式改名为“普林斯顿大学”。截止至2019年，普林斯顿大学共培养了2位美国总统、12位美国最高法院大法官以及众多美国国会议员。 截止2020年3月，普林斯顿大学的校友、教授及研究人员中，共产生了68位诺贝尔奖获得主（世界第十）、15位世界数学最高奖菲尔兹奖得主（世界第三）、14位世界计算机最高奖图灵奖得主（世界第四）。2019-2020年，普林斯顿大学位列U.S. News美国最佳大学排名全美第一，软科世界大学学术排名世界第6、THE世界大学排名世界第6、U.S. News世界大学排名世界第8、QS世界大学排名世界第13；THE世界大学声誉排名世界第7。2020年莫斯科国际大学排名世界第25，2021年QS世界大学排名世界第12。,私立,美国,15,Computer Science-Machine Learning,"否,作为研究方向",学术型硕士,https://www.cs.princeton.edu/grad/m.s.e.-track,The School of Engineering and Applied Science,"Department of
COMPUTER SCIENCE",,https://www.princeton.edu/admission-aid/graduate-admission,Master of Science in Engineering,2years,否,6 courseswork,https://gradschool.princeton.edu/academics/degrees-requirements/fields-study/computer-science,,,否,是,否,https://www.cs.princeton.edu/grad/m.s.e.-track,https://aiml.cs.princeton.edu/,
20,普林斯顿大学,Princeton University,普林斯顿大学（Princeton University），简称“普林斯顿”，是世界著名私立研究型大学，位于美国东海岸新泽西州的普林斯顿市，是美国大学协会的14个始创院校之一，也是著名的常春藤联盟成员。基督教教会曙光长老会于1746年在新泽西州伊丽莎白镇创立该校，是美国殖民时期第四所成立的高等院校，当时名为“新泽西学院（College of New Jersey）”。1747年学校迁至新泽西州，1756年迁至风景优美的普林斯顿市（位于费城和纽约之间），并在1896年正式改名为“普林斯顿大学”。截止至2019年，普林斯顿大学共培养了2位美国总统、12位美国最高法院大法官以及众多美国国会议员。 截止2020年3月，普林斯顿大学的校友、教授及研究人员中，共产生了68位诺贝尔奖获得主（世界第十）、15位世界数学最高奖菲尔兹奖得主（世界第三）、14位世界计算机最高奖图灵奖得主（世界第四）。2019-2020年，普林斯顿大学位列U.S. News美国最佳大学排名全美第一，软科世界大学学术排名世界第6、THE世界大学排名世界第6、U.S. News世界大学排名世界第8、QS世界大学排名世界第13；THE世界大学声誉排名世界第7。2020年莫斯科国际大学排名世界第25，2021年QS世界大学排名世界第12。,私立,美国,15,Computer Science-Machine Learning,"否,作为研究方向",博士,https://www.cs.princeton.edu/grad/doctoral-degree,The School of Engineering and Applied Science,"Department of
COMPUTER SCIENCE",,https://www.princeton.edu/admission-aid/graduate-admission,Doctor of Philosophy,5-6 years,否,6 courseswork,https://www.cs.princeton.edu/grad/fpo-checklist,,,否,是,否,https://www.cs.princeton.edu/grad/competency,https://aiml.cs.princeton.edu/,
21,加州理工学院,California Institute of Technology,加州理工学院（California Institute of Technology），简称“Caltech”，创立于1891年，位于美国加利福尼亚州洛杉矶东北郊的帕萨迪纳（Pasadena），是世界顶尖的私立研究型大学。 该校在全球科技界久负盛名，曾于2012至2016年间连续5年位列泰晤士高等教育世界大学排名世界第1，2019-20年度排名世界第2，在物理学、化学、天文学和空间科学等领域均为世界顶级，还协助美国航空航天局（NASA）负责管理著名的喷气推进实验室。加州理工学院的规模很小，全校学生仅2000人左右，是一所典型的精英学府。截至2019年10月，该校共有74位校友、教授及研究人员曾获得诺贝尔奖（世界第八），其中包括22位校友，平均每千名毕业生就有一人获奖（22位校友），为世界大学诺贝尔奖得主密度之冠。加州理工学院还产生了6位图灵奖得主（世界第九）以及4位菲尔兹奖得主（世界第十六）。加州理工学院位列2020年QS世界大学排名世界第5、U.S. News世界大学排名世界第6、软科世界大学学术排名世界第9、莫斯科国际大学排名世界第27，其中地球科学学科位列世界第2、物理学世界第6、化学世界第5、航空航天工程世界第6。 “中国航天之父”、“中国导弹之父”钱学森1939年获得加州理工学院博士学位并在此长期任教，亦参与创建了喷气推进实验室。 该校还是CBS美剧《生活大爆炸》的故事背景地。,私立,美国,21,Computer Science-Machine Learning ,"否,作为研究方向",学士,https://www.cms.caltech.edu/academics/ugrad/ugrad_cs,"Division of
Engineering and Applied Science",Computing & Mathematical Sciences department,,https://www.admissions.caltech.edu/,Bachelor of Science in Computer Science,4years,否,486 units,https://www.cms.caltech.edu/academics/courses/cs-80-abc,"1.understand information and computation as intrinsic components of a broad array of natural and engineered systems
2.tackle challenging and fundamental problems with the potential for long-term and real-world impact
3.develop underlying theory
nurture collaboration between traditionally separate disciplines","a thorough understanding of the mathematical and algorithmic foundations of computer science,
a depth of knowledge, and an understanding of the research frontiers, in at least one subfield of computer science,
experience in working on a significant project, typically as part of a team,
an appreciation of the scope of applications of computing in information systems and across science and engineering,
an ability to apply computational thinking to a wide variety of problems both inside and outside Computer Science,
an understanding of how to critically evaluate computer science research
an ability to effectively communicate their ideas in writing and in oral presentations.",否,否,是,https://catalog.caltech.edu/current/information-for-undergraduate-students/graduation-requirements-all-options/computer-science-option-and-minor-cs/,https://www.cms.caltech.edu/research/artificial-intelligence-and-machine-learning,
22,加州理工学院,California Institute of Technology,加州理工学院（California Institute of Technology），简称“Caltech”，创立于1891年，位于美国加利福尼亚州洛杉矶东北郊的帕萨迪纳（Pasadena），是世界顶尖的私立研究型大学。 该校在全球科技界久负盛名，曾于2012至2016年间连续5年位列泰晤士高等教育世界大学排名世界第1，2019-20年度排名世界第2，在物理学、化学、天文学和空间科学等领域均为世界顶级，还协助美国航空航天局（NASA）负责管理著名的喷气推进实验室。加州理工学院的规模很小，全校学生仅2000人左右，是一所典型的精英学府。截至2019年10月，该校共有74位校友、教授及研究人员曾获得诺贝尔奖（世界第八），其中包括22位校友，平均每千名毕业生就有一人获奖（22位校友），为世界大学诺贝尔奖得主密度之冠。加州理工学院还产生了6位图灵奖得主（世界第九）以及4位菲尔兹奖得主（世界第十六）。加州理工学院位列2020年QS世界大学排名世界第5、U.S. News世界大学排名世界第6、软科世界大学学术排名世界第9、莫斯科国际大学排名世界第27，其中地球科学学科位列世界第2、物理学世界第6、化学世界第5、航空航天工程世界第6。 “中国航天之父”、“中国导弹之父”钱学森1939年获得加州理工学院博士学位并在此长期任教，亦参与创建了喷气推进实验室。 该校还是CBS美剧《生活大爆炸》的故事背景地。,私立,美国,21,Computer Science-Machine Learning ,"否,作为研究方向",博士,https://www.cms.caltech.edu/academics/grad/grad_cs,"Division of
Engineering and Applied Science",Computing & Mathematical Sciences department,,https://gradoffice.caltech.edu/admissions/applyonline,Doctor of Philosophy in Computer Science,6years,否,135 units,https://catalog.caltech.edu/current/information-for-graduate-students/special-regulations-for-graduate-options/computer-science-cs/,"1.understand information and computation as intrinsic components of a broad array of natural and engineered systems
2.tackle challenging and fundamental problems with the potential for long-term and real-world impact
3.develop underlying theory
nurture collaboration between traditionally separate disciplines","a thorough understanding of the mathematical and algorithmic foundations of computer science,
cutting-edge knowledge in the area of research specialization,
the ability to identify, formulate, and tackle problems at the research frontiers in the area of specialization,
success and originality in the formulation, analysis, and solution of a problem that is significant to the area of research specialization,
experience in critically evaluating computer science research,
experience in effectively communicate their ideas in writing and in oral presentations.",否,否,是,https://www.cms.caltech.edu/documents/4568/Navigating.the.PhD.Options.in.CMS.pdf,https://www.cms.caltech.edu/research/artificial-intelligence-and-machine-learning,https://www.cms.caltech.edu/documents/4568/Navigating.the.PhD.Options.in.CMS.pdf
23,芝加哥大学,The University of Chicago,芝加哥大学（The University of Chicago），简称“芝大”（UChicago），世界顶尖私立研究型大学，常年稳居多家世界大学排行榜前十位，坐落于美国国际金融中心芝加哥。该校诞生了芝加哥经济学派等众多知名的芝加哥学派，创立了法律经济学，是经济学、法学等社会科学学科的世界级学术重镇；而从曼哈顿计划起大批科学家汇集于此，在“原子能之父”恩利克·费米等人的领导下建立了世界上第一台核反应堆（芝加哥一号堆），开启了人类原子能时代，并创办了美国第一所国家实验室阿贡国家实验室和著名的费米实验室，奠定了芝大在自然科学界的重要地位。芝加哥大学于1890年由石油大王约翰·洛克菲勒创办，素以盛产诺贝尔奖得主而闻名，约40%的诺贝尔经济学奖得主与芝大相关。截至至2019年10月，芝加哥大学的校友、教授及研究人员中，共产生了100位诺奖得主、位列世界第四。华裔诺贝尔物理学奖得主杨振宁、李政道、崔琦均在芝加哥大学取得物理学博士学位，另有9位菲尔兹奖得主（世界第七）、4位图灵奖得主及25位普利策奖得主曾在芝大工作或学习。美国第44任总统奥巴马曾长期在芝大法学院教授宪法（1992-2004年）。2019-20年度，芝加哥大学位列U.S. News美国最佳大学排名第6、THE世界大学声誉排名第10。2020-21年度，U.S. News世界大学排名第13、软科世界大学学术排名第10、THE世界大学排名第10、QS世界大学排名第9。,私立,美国,35,Computer Science-AI&Machine Learning,"否,作为研究方向",学士,http://collegecatalog.uchicago.edu/thecollege/computerscience/,The College ,department of computer science,,https://collegeadmissions.uchicago.edu/apply,Bachelor of Science,4years,否,4200units,https://cs.uchicago.edu/academics/undergraduate/bx-thesis-program/,prepares students for either graduate work or employment in computer science.,Recipients of the BS will also have substantial depth and breadth in a field outside of computer science through the completion of an approved related area.,否,否,是,http://collegecatalog.uchicago.edu/thecollege/computerscience/,https://cs.uchicago.edu/people/uchicago-faculty/full-time-faculty/?_research_fselect=ai-machine-learning,
24,芝加哥大学,The University of Chicago,芝加哥大学（The University of Chicago），简称“芝大”（UChicago），世界顶尖私立研究型大学，常年稳居多家世界大学排行榜前十位，坐落于美国国际金融中心芝加哥。该校诞生了芝加哥经济学派等众多知名的芝加哥学派，创立了法律经济学，是经济学、法学等社会科学学科的世界级学术重镇；而从曼哈顿计划起大批科学家汇集于此，在“原子能之父”恩利克·费米等人的领导下建立了世界上第一台核反应堆（芝加哥一号堆），开启了人类原子能时代，并创办了美国第一所国家实验室阿贡国家实验室和著名的费米实验室，奠定了芝大在自然科学界的重要地位。芝加哥大学于1890年由石油大王约翰·洛克菲勒创办，素以盛产诺贝尔奖得主而闻名，约40%的诺贝尔经济学奖得主与芝大相关。截至至2019年10月，芝加哥大学的校友、教授及研究人员中，共产生了100位诺奖得主、位列世界第四。华裔诺贝尔物理学奖得主杨振宁、李政道、崔琦均在芝加哥大学取得物理学博士学位，另有9位菲尔兹奖得主（世界第七）、4位图灵奖得主及25位普利策奖得主曾在芝大工作或学习。美国第44任总统奥巴马曾长期在芝大法学院教授宪法（1992-2004年）。2019-20年度，芝加哥大学位列U.S. News美国最佳大学排名第6、THE世界大学声誉排名第10。2020-21年度，U.S. News世界大学排名第13、软科世界大学学术排名第10、THE世界大学排名第10、QS世界大学排名第10。,私立,美国,35,Computer Science-AI&Machine Learning,"否,作为研究方向",专业型硕士,https://cs.uchicago.edu/academics/masters/mpcs/mpcs-programs-of-study/,The College,department of computer science,,https://apply-psd.uchicago.edu/apply/,Master of Science in computer science,9months-1years,否,9courses：900units/12courses:1200units,,to provide students a deep foundation in computer science and the essentials skills required for a successful career in technology.,Graduates of the MPCS are in demand by top companies for their ability to contribute immediately in technically challenging roles as well as to adapt quickly to rapidly evolving technologies.,否,12门课程项目需要实习,否,https://mpcs-internal.cs.uchicago.edu/page/curriculum-and-degree-requirements,https://cs.uchicago.edu/people/uchicago-faculty/full-time-faculty/?_research_fselect=ai-machine-learning,
25,芝加哥大学,The University of Chicago,芝加哥大学（The University of Chicago），简称“芝大”（UChicago），世界顶尖私立研究型大学，常年稳居多家世界大学排行榜前十位，坐落于美国国际金融中心芝加哥。该校诞生了芝加哥经济学派等众多知名的芝加哥学派，创立了法律经济学，是经济学、法学等社会科学学科的世界级学术重镇；而从曼哈顿计划起大批科学家汇集于此，在“原子能之父”恩利克·费米等人的领导下建立了世界上第一台核反应堆（芝加哥一号堆），开启了人类原子能时代，并创办了美国第一所国家实验室阿贡国家实验室和著名的费米实验室，奠定了芝大在自然科学界的重要地位。芝加哥大学于1890年由石油大王约翰·洛克菲勒创办，素以盛产诺贝尔奖得主而闻名，约40%的诺贝尔经济学奖得主与芝大相关。截至至2019年10月，芝加哥大学的校友、教授及研究人员中，共产生了100位诺奖得主、位列世界第四。华裔诺贝尔物理学奖得主杨振宁、李政道、崔琦均在芝加哥大学取得物理学博士学位，另有9位菲尔兹奖得主（世界第七）、4位图灵奖得主及25位普利策奖得主曾在芝大工作或学习。美国第44任总统奥巴马曾长期在芝大法学院教授宪法（1992-2004年）。2019-20年度，芝加哥大学位列U.S. News美国最佳大学排名第6、THE世界大学声誉排名第10。2020-21年度，U.S. News世界大学排名第13、软科世界大学学术排名第10、THE世界大学排名第10、QS世界大学排名第10。,私立,美国,35,Computer Science-AI&Machine Learning,"否,作为研究方向",学术型硕士,http://cs.uchicago.edu/mpcs-pre-doctoral-program/,The College,department of computer science,,https://apply-psd.uchicago.edu/apply/,Master of Science in computer science,15months,否,1200units,,to provide students a deep foundation in computer science and the essentials skills required for a successful career in technology.,Graduates of the MPCS are in demand by top companies for their ability to contribute immediately in technically challenging roles as well as to adapt quickly to rapidly evolving technologies.,否,是,否,https://mpcs-internal.cs.uchicago.edu/page/mpcs-course-catalog-0,https://cs.uchicago.edu/people/uchicago-faculty/full-time-faculty/?_research_fselect=ai-machine-learning,
26,芝加哥大学,The University of Chicago,芝加哥大学（The University of Chicago），简称“芝大”（UChicago），世界顶尖私立研究型大学，常年稳居多家世界大学排行榜前十位，坐落于美国国际金融中心芝加哥。该校诞生了芝加哥经济学派等众多知名的芝加哥学派，创立了法律经济学，是经济学、法学等社会科学学科的世界级学术重镇；而从曼哈顿计划起大批科学家汇集于此，在“原子能之父”恩利克·费米等人的领导下建立了世界上第一台核反应堆（芝加哥一号堆），开启了人类原子能时代，并创办了美国第一所国家实验室阿贡国家实验室和著名的费米实验室，奠定了芝大在自然科学界的重要地位。芝加哥大学于1890年由石油大王约翰·洛克菲勒创办，素以盛产诺贝尔奖得主而闻名，约40%的诺贝尔经济学奖得主与芝大相关。截至至2019年10月，芝加哥大学的校友、教授及研究人员中，共产生了100位诺奖得主、位列世界第四。华裔诺贝尔物理学奖得主杨振宁、李政道、崔琦均在芝加哥大学取得物理学博士学位，另有9位菲尔兹奖得主（世界第七）、4位图灵奖得主及25位普利策奖得主曾在芝大工作或学习。美国第44任总统奥巴马曾长期在芝大法学院教授宪法（1992-2004年）。2019-20年度，芝加哥大学位列U.S. News美国最佳大学排名第6、THE世界大学声誉排名第10。2020-21年度，U.S. News世界大学排名第13、软科世界大学学术排名第10、THE世界大学排名第10、QS世界大学排名第11。,私立,美国,36,Computer Science-AI&Machine Learning,"否,作为研究方向",学士和硕士,https://cs.uchicago.edu/academics/undergraduate/joint-bx-ms-programs/,The College,department of computer science,,https://urldefense.com/v3/__https://uchicago.app.box.com/s/1w99h7hs33l3l7j19eoh9zpqujf133do__;!!BpyFHLRN4TMTrA!70W0D6OL02T_s30A3M7D7I8G-a6AUwJ3YOj-wJCDHwltdv_a_OhOea3ucnGHExgLjPQldz80tk2A2-l_tYgXGgLamjE$,Bachelor/Master of Science in computer science,4years,是,4900units,,"There are three different paths to a Bx/MS: a research-oriented program for computer science majors (Option 1 below), a professionally oriented program for computer science majors (Option 2), and a professionally oriented program for non-majors (Option 3).",,否,否,否,https://course-info.cs.uchicago.edu/,https://cs.uchicago.edu/people/uchicago-faculty/full-time-faculty/?_research_fselect=ai-machine-learning,
27,芝加哥大学,The University of Chicago,芝加哥大学（The University of Chicago），简称“芝大”（UChicago），世界顶尖私立研究型大学，常年稳居多家世界大学排行榜前十位，坐落于美国国际金融中心芝加哥。该校诞生了芝加哥经济学派等众多知名的芝加哥学派，创立了法律经济学，是经济学、法学等社会科学学科的世界级学术重镇；而从曼哈顿计划起大批科学家汇集于此，在“原子能之父”恩利克·费米等人的领导下建立了世界上第一台核反应堆（芝加哥一号堆），开启了人类原子能时代，并创办了美国第一所国家实验室阿贡国家实验室和著名的费米实验室，奠定了芝大在自然科学界的重要地位。芝加哥大学于1890年由石油大王约翰·洛克菲勒创办，素以盛产诺贝尔奖得主而闻名，约40%的诺贝尔经济学奖得主与芝大相关。截至至2019年10月，芝加哥大学的校友、教授及研究人员中，共产生了100位诺奖得主、位列世界第四。华裔诺贝尔物理学奖得主杨振宁、李政道、崔琦均在芝加哥大学取得物理学博士学位，另有9位菲尔兹奖得主（世界第七）、4位图灵奖得主及25位普利策奖得主曾在芝大工作或学习。美国第44任总统奥巴马曾长期在芝大法学院教授宪法（1992-2004年）。2019-20年度，芝加哥大学位列U.S. News美国最佳大学排名第6、THE世界大学声誉排名第10。2020-21年度，U.S. News世界大学排名第13、软科世界大学学术排名第10、THE世界大学排名第10、QS世界大学排名第9。,私立,美国,35,Computer Science-AI&Machine Learning,"否,作为研究方向",博士,https://cs.uchicago.edu/academics/phd/phd-program-overview/,The College ,department of computer science,,https://apply-psd.uchicago.edu/apply/,Doctor of Philosophy in Science,6years,否,800units,https://cs.uchicago.edu/academics/phd/phd-program-overview/dissertation-defense/,or students to acquire the skills to produce successful research in Computer Science,"build the skills to conduct research at the cutting edge of computer science, working with faculty to publish at leading conferences, develop new tools and approaches, and make bold new discoveries across research areas.",否,否,是,https://cs.uchicago.edu/academics/phd/course-requirements/,https://cs.uchicago.edu/people/uchicago-faculty/full-time-faculty/?_research_fselect=ai-machine-learning,
28,康奈尔大学,Cornell University,康奈尔大学（Cornell University），位于美国纽约州伊萨卡，是一所世界顶级私立研究型大学（另有两个校区位于纽约市和卡塔尔教育城），为美国大学协会的十四个创始院校之一，以及著名的常春藤盟校的八个成员之一。康奈尔大学由埃兹拉·康奈尔和安德鲁·迪克森·怀特于1865年建立，是常春藤八盟校中唯一创建于美国独立战争之后的新生力量，其办学理念影响了整个美国高等教育，办学规模为当时全美高校之最。康奈尔大学的立校之本是任何人都有获得教育的平等权利，是常春藤盟校中第一所实行性别平等的男女合校大学，在招生录取上最早实行不计贵族身份，不分信仰和种族，并以创建学科齐全、包罗万象的新型综合性大学为建校宗旨。康奈尔大学是一所采用公私合营的办学模式的大学，最初以农工学院为特色而起家，其酒店管理学院、工业与劳工关系学院为全美首创。康奈尔大学专业包括农业、兽医、工科、计算机科学、劳工关系、文理、经济、建筑、城市规划、教育、商科、传媒、以及酒店管理等。截止2018年，共有58位康奈尔大学的校友或教研人员曾荣获诺贝尔奖，在全球高校中列第十二位，居全美第十位。2019-20年度，位列2020QS世界大学排名世界第14，2019软科世界大学学术排名世界第13，2020莫斯科国际大学排名世界第18，2020年THE世界大学排名世界第19，2020U.S. News世界大学排名世界第23；2019福布斯美国大学排行榜第11，2020U.S. News美国最佳大学排名第17。2021年QS世界大学排名世界第18。,私立,美国,16,Computer Science-Artificial Intelligence,"否,作为研究方向",学术型硕士,http://www.cs.cornell.edu/ms,Cornell Ann S. Bowers College of Computing and Information Science. ,Department of Computer Science,,https://gradschool.cornell.edu/admissions/apply/apply-now/,Master of Science in computer science ,2years,否,34units,https://gradschool.cornell.edu/academic-progress/requirements/making-academic-progress/defending-your-thesis-or-dissertation/,"for students who wish to deepen their knowledge of computer science through advanced coursework, research, writing, and teaching.","Demonstrate knowledge at the undergraduate level of four core areas in computer science

Systems, AI, PL, and theory
Students should be able to solve problems in these four core areas at the undergraduate level.
Demonstrate knowledge, understanding, applications, analysis, and evaluation of material at the graduate level in four out of five important core areas of computer science

The five different core areas are as follows: algorithms and theory of computation, artificial intelligence, systems, programming languages and methodology, scientific computing and applications
Demonstrate knowledge, understanding, applications, analysis, and evaluation of the three different value systems of the three computer science research styles that differ in how they evaluate and validate research results

The three different styles are: theory, systems, and applied",否,否,否,https://www.cs.cornell.edu/courseinfo/listofcscourses,https://gradschool.cornell.edu/academics/fields-of-study/field/computer-science/,
29,康奈尔大学,Cornell University,康奈尔大学（Cornell University），位于美国纽约州伊萨卡，是一所世界顶级私立研究型大学（另有两个校区位于纽约市和卡塔尔教育城），为美国大学协会的十四个创始院校之一，以及著名的常春藤盟校的八个成员之一。康奈尔大学由埃兹拉·康奈尔和安德鲁·迪克森·怀特于1865年建立，是常春藤八盟校中唯一创建于美国独立战争之后的新生力量，其办学理念影响了整个美国高等教育，办学规模为当时全美高校之最。康奈尔大学的立校之本是任何人都有获得教育的平等权利，是常春藤盟校中第一所实行性别平等的男女合校大学，在招生录取上最早实行不计贵族身份，不分信仰和种族，并以创建学科齐全、包罗万象的新型综合性大学为建校宗旨。康奈尔大学是一所采用公私合营的办学模式的大学，最初以农工学院为特色而起家，其酒店管理学院、工业与劳工关系学院为全美首创。康奈尔大学专业包括农业、兽医、工科、计算机科学、劳工关系、文理、经济、建筑、城市规划、教育、商科、传媒、以及酒店管理等。截止2018年，共有58位康奈尔大学的校友或教研人员曾荣获诺贝尔奖，在全球高校中列第十二位，居全美第十位。2019-20年度，位列2020QS世界大学排名世界第14，2019软科世界大学学术排名世界第13，2020莫斯科国际大学排名世界第18，2020年THE世界大学排名世界第19，2020U.S. News世界大学排名世界第23；2019福布斯美国大学排行榜第11，2020U.S. News美国最佳大学排名第17。2021年QS世界大学排名世界第18。,私立,美国,16,Computer Science-Artificial Intelligence,"否,作为研究方向",专业型硕士,https://www.cs.cornell.edu/masters,Cornell Ann S. Bowers College of Computing and Information Science. ,Department of Computer Science,,https://gradschool.cornell.edu/admissions/apply/,Master of Engineering in Computer Science,1years,否,30units,,designed to enhance practical skills.,"Mastery and Application of Core Disciplinary Knowledge
Problem Formulation, Organization, and Planning of the Solution Process
Collaborative Problem Solving and Issue Resolution
Communication of Knowledge, Ideas, and Decision Justification
Self-directed Learning and Professional Development",是,否,是,https://www.cs.cornell.edu/courseinfo/listofcscourses,https://gradschool.cornell.edu/academics/fields-of-study/field/computer-science/,
30,康奈尔大学,Cornell University,康奈尔大学（Cornell University），位于美国纽约州伊萨卡，是一所世界顶级私立研究型大学（另有两个校区位于纽约市和卡塔尔教育城），为美国大学协会的十四个创始院校之一，以及著名的常春藤盟校的八个成员之一。康奈尔大学由埃兹拉·康奈尔和安德鲁·迪克森·怀特于1865年建立，是常春藤八盟校中唯一创建于美国独立战争之后的新生力量，其办学理念影响了整个美国高等教育，办学规模为当时全美高校之最。康奈尔大学的立校之本是任何人都有获得教育的平等权利，是常春藤盟校中第一所实行性别平等的男女合校大学，在招生录取上最早实行不计贵族身份，不分信仰和种族，并以创建学科齐全、包罗万象的新型综合性大学为建校宗旨。康奈尔大学是一所采用公私合营的办学模式的大学，最初以农工学院为特色而起家，其酒店管理学院、工业与劳工关系学院为全美首创。康奈尔大学专业包括农业、兽医、工科、计算机科学、劳工关系、文理、经济、建筑、城市规划、教育、商科、传媒、以及酒店管理等。截止2018年，共有58位康奈尔大学的校友或教研人员曾荣获诺贝尔奖，在全球高校中列第十二位，居全美第十位。2019-20年度，位列2020QS世界大学排名世界第14，2019软科世界大学学术排名世界第13，2020莫斯科国际大学排名世界第18，2020年THE世界大学排名世界第19，2020U.S. News世界大学排名世界第23；2019福布斯美国大学排行榜第11，2020U.S. News美国最佳大学排名第17。2021年QS世界大学排名世界第19。,私立,美国,16,Computer Science-Artificial Intelligence,"否,作为研究方向",博士,http://www.cs.cornell.edu/phd,Cornell Ann S. Bowers College of Computing and Information Science. ,"Department of Computer Science，Electrical Engineering, Information Science, Applied Math, Mathematics, Operations Research and Industrial Engineering, Mechanical and Aerospace Engineering, Computational Biology, and Architecture",,https://gradschool.cornell.edu/admissions/apply/,Doctor of Philosophy  in Computer Science,4-7years,否,,https://gradschool.cornell.edu/academic-progress/requirements/making-academic-progress/defending-your-thesis-or-dissertation/,,"Demonstrate knowledge at the undergraduate level of four core areas in the computer science

Systems, AI, PL, and theory
Students should be able to solve problems in these four core areas at the undergraduate level
Demonstrate knowledge, understanding, applications, analysis, and evaluation of material at the graduate level in four out of five important core areas of computer science

The five different core areas are as follows: algorithms and theory of computation, artificial intelligence, systems, programming languages and methodology, scientific computing and applications
Demonstrate knowledge, understanding, applications, analysis, and evaluation of the three different value systems of the three computer science research styles that differ in how they evaluate and validate research results

The three different research styles are theory, systems, and applications.
Complete a significant computer science project. ",是,否,是,,https://gradschool.cornell.edu/academics/fields-of-study/field/computer-science/,
31,纽约大学,New York University,纽约大学（New York University），简称NYU，是一所位于美国纽约市的世界顶尖私立研究型大学，全美办学规模最大的私立名校之一，同时在伦敦、布宜诺斯艾利斯、悉尼、柏林、巴黎、布拉格、华盛顿哥伦比亚特区等地共设立11个全球学术中心。该校系新常春藤名校之一，美国大学协会成员并以培育创新才能的教育理念著称，在2019QS毕业生就业能力排名世界第11位 ，著名校友总数排名全美第8位,私立,美国,17,Computer Science-Data Science / AI / Robotics,"否,作为研究方向",学士,https://engineering.nyu.edu/academics/programs/computer-engineering-bs,Tandon School of Engineeringc,computer science and engineering department,ABET Accredited,https://www.nyu.edu/admissions/undergraduate-admissions/how-to-apply.html,Bachelor of Science in Computer Engineering,4years,否,128 units,,"Graduates are expected to be engaged and advancing in their professional careers in a profession that utilizes their NYU Tandon degree, in Computer Engineering or another career path, that include industry, academia, and governmental or non-governmental organizations.","Upon successful completion of the program, graduates will have:
An ability to identify, formulate, and solve complex engineering problems by applying principles of engineering, science, and mathematics.
An ability to apply engineering design to produce solutions that meet specified needs with consideration of public health, safety, and welfare, as well as global, cultural, social, environmental, and economic factors.
An ability to communicate effectively with a range of audiences.
An ability to recognize ethical and professional responsibilities in engineering situations and make informed judgments, which must consider the impact of engineering solutions in global, economic, environmental, and societal contexts.
An ability to function effectively on a team whose members together provide leadership, create a collaborative and inclusive environment, establish goals, plan tasks, and meet objectives.
An ability to develop and conduct appropriate experimentation, analyze and interpret data, and use engineering judgment to draw conclusions.
An ability to acquire and apply new knowledge as needed, using appropriate learning strategies.",否,否,是,https://bulletins.nyu.edu/undergraduate/engineering/programs/computer-science-bs/#curriculumtext,https://nyuad.nyu.edu/en/academics/divisions/science/faculty.html?_charset_=UTF-8&program=computer-science-major&affiliation=&keywords=,https://gradschool.cornell.edu/academics/fields-of-study/field/computer-science
32,纽约大学,New York University,纽约大学（New York University），简称NYU，是一所位于美国纽约市的世界顶尖私立研究型大学，全美办学规模最大的私立名校之一，同时在伦敦、布宜诺斯艾利斯、悉尼、柏林、巴黎、布拉格、华盛顿哥伦比亚特区等地共设立11个全球学术中心。该校系新常春藤名校之一，美国大学协会成员并以培育创新才能的教育理念著称，在2019QS毕业生就业能力排名世界第11位 ，著名校友总数排名全美第8位,私立,美国,17,Computer Science-Data Science / AI / Robotics,"否,作为研究方向",专业型硕士,https://engineering.nyu.edu/academics/programs/computer-science-ms,Tandon School of Engineeringc,computer science and engineering department,,https://apply.engineering.nyu.edu/apply/?_gl=1*1xz9zm0*_ga*MzMyNzMxODMuMTcxNDQ4MzI5NA..*_ga_2YVHNYZEDV*MTcxNDUzNTMyNi4zLjEuMTcxNDUzNzMwNy41OS4wLjA.,Master of science in Computer Science ,2-2.5years,否,30units,,We offer a highly adaptive M.S. in Computer Science program that lets you shape the degree around your interests.,"Upon successful completion of the program, graduates will:
Develop laboratory software skills for graduate level work.
Learn advanced fundamentals in computer systems.
Learn advanced fundamentals in computer science theory.
Learn advanced fundamentals in software/programming.
Broaden their backgrounds by taking important electives to further their special interest knowledge. ",否,否,否,https://bulletins.nyu.edu/graduate/engineering/programs/computer-engineering-ms/#curriculumtext,https://engineering.nyu.edu/academics/departments/computer-science-and-engineering/people,
33,纽约大学,New York University,纽约大学（New York University），简称NYU，是一所位于美国纽约市的世界顶尖私立研究型大学，全美办学规模最大的私立名校之一，同时在伦敦、布宜诺斯艾利斯、悉尼、柏林、巴黎、布拉格、华盛顿哥伦比亚特区等地共设立11个全球学术中心。该校系新常春藤名校之一，美国大学协会成员并以培育创新才能的教育理念著称，在2019QS毕业生就业能力排名世界第11位 ，著名校友总数排名全美第8位,私立,美国,17,Computer Science-Data Science / AI / Robotics,"否,作为研究方向",博士,https://engineering.nyu.edu/academics/programs/computer-science-phd,Tandon School of Engineeringc,computer science and engineering department,,https://apply.engineering.nyu.edu/apply/?_gl=1*1a6lr1s*_ga*MzMyNzMxODMuMTcxNDQ4MzI5NA..*_ga_2YVHNYZEDV*MTcxNDcwNTA0My40LjEuMTcxNDcwNjUxNC40MC4wLjA.,Doctor of Philosophy degrees in Computer Science,6years,否,75units,,,"Upon successful completion of the program, graduates will have:

A broad knowledge of computer science.
The ability to conduct original research in computer science.
The ability to present their research in written papers and oral presentations.",否,否,否,https://bulletins.nyu.edu/graduate/engineering/programs/computer-science-phd/#curriculumtext,https://engineering.nyu.edu/academics/departments/computer-science-and-engineering/people,
34,宾夕法尼亚大学,University of Pennsylvania,宾夕法尼亚大学（University of Pennsylvania ），简称宾大（UPenn），位于宾夕法尼亚州最大城市费城，是一所全球顶尖的私立研究型大学，著名的八所常春藤盟校之一，北美顶尖大学学术联盟美国大学协会14所创始成员之一。宾大由本杰明·富兰克林创建于1740年，是美国第四古老的高等教育机构，也是美国第一所从事科学技术和人文教育的现代高等学校。1765年成立全美第一所医学院、1881年成立全美第一所商学院、1896成立全美第一个学生会组织，在至今数百年的学校历史中，宾大一次又一次在教育以及科学技术上推动了人类文明的发展，诞生了人类历史上第一台通用电子计算机ENIAC，被誉为现代计算机科学文明的发源地，以及风疹疫苗、乙肝疫苗、认知心理疗法等的发明挽救了无数生命。宾大拥有全世界最强大的校友网络之一，包括数十位在各自领域的最高奖项获得者（如诺贝尔奖、图灵奖等）以及许多美国国家院士。宾夕法尼亚大学名列2019福布斯美国大学排行榜第6名，2020U.S. News美国最佳大学排名第6名，2020莫斯科国际大学排名第5名，2020U.S. News世界大学排名第14名，2020THE世界大学排名第11名，被普林斯顿评论评为十大梦想学校之一。根据研究经费及师生质量等学术指标，2014年，大学评定中心把宾大评为研究实力一级研究型大学（并列一级另有哥大、哈佛、麻省理工和斯坦福四所高校）。根据2017年公布的福布斯富豪榜，宾大培养的亿万富豪校友数量位居全美第一，超过哈佛大学和斯坦福大学。,私立,美国,20,Artificial Intelligence,是,学士,https://ai.seas.upenn.edu/,School of Engineering and Applied Science,Departments of Electrical and Systems Engineering (ESE) and Computer and Information Science (CIS),The First Ivy League Bachelor of Science in Engineering in Artificial Intelligence,https://admissions.upenn.edu/how-to-apply/apply-for-admissions,B.S.E. in Artificial Intelligence,4years,否,37units,,"Complementing these engineering skills with a broader perspective, students learn about intelligence from a cognitive science perspective, and they develop a sense of the issues (and solutions) required to responsibly develop AI to benefit society. "," Finally, students choose a concentration, ranging from machine learning, to vision and language, to data and society, to robotics, to AI and health systems.",否,否,是,https://ai.seas.upenn.edu/curriculum/,https://directory.seas.upenn.edu/computer-and-information-science/,https://ugrad.seas.upenn.edu/student-handbook/
35,宾夕法尼亚大学,University of Pennsylvania,宾夕法尼亚大学（University of Pennsylvania ），简称宾大（UPenn），位于宾夕法尼亚州最大城市费城，是一所全球顶尖的私立研究型大学，著名的八所常春藤盟校之一，北美顶尖大学学术联盟美国大学协会14所创始成员之一。宾大由本杰明·富兰克林创建于1740年，是美国第四古老的高等教育机构，也是美国第一所从事科学技术和人文教育的现代高等学校。1765年成立全美第一所医学院、1881年成立全美第一所商学院、1896成立全美第一个学生会组织，在至今数百年的学校历史中，宾大一次又一次在教育以及科学技术上推动了人类文明的发展，诞生了人类历史上第一台通用电子计算机ENIAC，被誉为现代计算机科学文明的发源地，以及风疹疫苗、乙肝疫苗、认知心理疗法等的发明挽救了无数生命。宾大拥有全世界最强大的校友网络之一，包括数十位在各自领域的最高奖项获得者（如诺贝尔奖、图灵奖等）以及许多美国国家院士。宾夕法尼亚大学名列2019福布斯美国大学排行榜第6名，2020U.S. News美国最佳大学排名第6名，2020莫斯科国际大学排名第5名，2020U.S. News世界大学排名第14名，2020THE世界大学排名第11名，被普林斯顿评论评为十大梦想学校之一。根据研究经费及师生质量等学术指标，2014年，大学评定中心把宾大评为研究实力一级研究型大学（并列一级另有哥大、哈佛、麻省理工和斯坦福四所高校）。根据2017年公布的福布斯富豪榜，宾大培养的亿万富豪校友数量位居全美第一，超过哈佛大学和斯坦福大学。,私立,美国,20,Artificial Intelligence,是,专业型硕士,https://online.seas.upenn.edu/degrees/mse-ai-online/,School of Engineering and Applied Science,online,,https://gradadmissions.seas.upenn.edu/apply/?sr=f695ac0b-595b-4ee1-9617-0571b6fdb029,Master of Science in Engineering in AI Online,,否,10units,,"equips you with technical skills including classical AI, natural language processing, generative AI, and modern deep learning, alongside a robust ethical framework, preparing you to shape the future of this transformative technology.",,否,否,否,https://online.seas.upenn.edu/course-catalog/mse-ai-online/,https://online.seas.upenn.edu/about/faculty-directory/,
36,约翰霍普金斯大学,The Johns Hopkins University,约翰斯·霍普金斯大学（Johns Hopkins University，简称Hopkins或JHU）创立于1876年，是世界第一所研究型大学，私立综合研究型大学，位于美国马里兰州巴尔的摩市，北美学术联盟美国大学协会（AAU）创始校之一。2023年U.S News全美最佳大学排名第七。2023年U.S News全球最佳大学排名第十。 ,私立,美国,27,"computer science-Machine Learning, AI, & Data Science","否,作为研究方向",学士,https://e-catalogue.jhu.edu/engineering/full-time-residential-programs/degree-programs/computer-science/computer-science-bs/,Whiting School of EngineeringDepartment of Computer Science,Department of Computer Science,ABET Accredited,https://apply.jhu.edu/,Bachelor of Science in computer science,4years,否,120units,,"The objectives of our bachelor degree programs are to train computer scientists who will be able to:

Successfully engage in professional practice in the computing sciences or apply computer science tools and techniques to solving problems in other disciplines.
Engage in continuous learning, including advanced study in the computing sciences. 
Work successfully in both independent and team environments, including diverse and interdisciplinary teams. 
Lead teams and provide vision for innovation.
Behave in a professional and ethical manner.
Practice inclusion and advocate for diversity. ","Analyze a complex computing problem and apply principles of computing and other relevant disciplines to identify solutions.
Design, implement, and evaluate a computing-based solution to meet a given set of computing requirements in the context of the program’s discipline.
Communicate effectively in a variety of professional contexts.
Recognize professional responsibilities and make informed judgments in computing practice based on legal and ethical principles.
Function effectively as a member or leader of a team engaged in activities appropriate to the program’s discipline.
Apply computer science theory and software development fundamentals to produce computing-based solutions.",否,否,是,https://e-catalogue.jhu.edu/engineering/full-time-residential-programs/degree-programs/computer-science/computer-science-bs/#requirementstext,https://www.cs.jhu.edu/research/machine-learning-ai-and-data-science/,https://www.cs.jhu.edu/academic-programs/undergraduate-studies/undergraduate-academics/undergraduate-academic-advising-manual-2021/
37,加利福尼亚大学圣地亚哥分校,University of California，San Diego,加利福尼亚大学（University of California），简称加州大学，是位于美国加利福尼亚州的一个由10所公立大学组成的大学行政系统，是世界上最具影响力的公立大学系统，被誉为“公立高等教育的典范”。加州大学起源于1853年建立在奥克兰的加利福尼亚学院（College of California），1868年3月正式更名为“加州大学”。1873年，学校迁入新址，为了纪念18世纪最伟大的哲学家之一乔治·贝克莱，新的大学城被命名为“伯克利市”，此后逐渐在洛杉矶等地开设分校区。1952年起，“加州大学”作为一个行政系统逐渐与伯克利加州大学分离。与此同时，加州各地的分校区也逐渐升格为与伯克利平级的、独立的大学。如今，加州大学已发展成一个拥有10所公立大学并对世界发展影响深远的大学系统。这些校区包括加州大学伯克利分校（UC Berkeley）、加州大学洛杉矶分校（UCLA）、加州大学圣地亚哥分校（UCSD）、加州大学旧金山分校（UCSF）、加州大学圣塔芭芭拉分校（UCSB）、加州大学尔湾分校（UCI）、加州大学戴维斯分校（UCD）、加州大学圣克鲁兹分校（UCSC）、加州大学河滨分校（UCR）和加州大学美熹德分校（UCM）。（注：现今的加州大学并没有所谓的“主校区”，“分校”一词只是中文翻译误区）加州大学是世界最大的大学联邦体，其旗下大学在各项学术指标和排名中均名列前茅。这些校区互为独立又紧密联系，各自作为独立的大学而存在，共同组成了享誉全美乃至全世界的加州大学。,公立,美国,31,Computer Science-Artificial Intelligence,"否,作为研究方向",学术型硕士,https://cse.ucsd.edu/graduate/degree-programs/ms-program,Jacob School of Engineering,Department of Computer Science and Engineering,Ranked #6 for Artificial Intelligence in CSRanking,https://cse.ucsd.edu/graduate/admissions,Master of Science in Computer Science and Engineering,1-2years,否,40units,https://cse.ucsd.edu/graduate/plan-i-thesis,"The educational mission of the Computer Science and Engineering Programs at UCSD is to provide our students with the computational, learning, teamwork, and communication skills to be productive and responsible members and leaders in computing and related industries.  ","Our graduates obtain skills and knowledge in five major areas (pillars):
    Oral and Written Communication 
    Modeling/Analysis #Mod 
    Problem framing + solving #Prob 
    Ethics/Impact #Pact
    Community/Processes/Teamwork 
The graduates of our BS program in CS and CE will be able to:Develop and contribute to large-scale programs and computational systems；Understand, guide, shape the impact of computing on society/the world；Reason about computation and systems；Know, select, and apply appropriate computing knowledge and problem-solving techniques
",是,否,否,https://cse.ucsd.edu/graduate/ms-plan-ii-comprehensive-exam-standard-option,https://ai.ucsd.edu/faculty,
38,加利福尼亚大学圣地亚哥分校,University of California，San Diego,加利福尼亚大学（University of California），简称加州大学，是位于美国加利福尼亚州的一个由10所公立大学组成的大学行政系统，是世界上最具影响力的公立大学系统，被誉为“公立高等教育的典范”。加州大学起源于1853年建立在奥克兰的加利福尼亚学院（College of California），1868年3月正式更名为“加州大学”。1873年，学校迁入新址，为了纪念18世纪最伟大的哲学家之一乔治·贝克莱，新的大学城被命名为“伯克利市”，此后逐渐在洛杉矶等地开设分校区。1952年起，“加州大学”作为一个行政系统逐渐与伯克利加州大学分离。与此同时，加州各地的分校区也逐渐升格为与伯克利平级的、独立的大学。如今，加州大学已发展成一个拥有10所公立大学并对世界发展影响深远的大学系统。这些校区包括加州大学伯克利分校（UC Berkeley）、加州大学洛杉矶分校（UCLA）、加州大学圣地亚哥分校（UCSD）、加州大学旧金山分校（UCSF）、加州大学圣塔芭芭拉分校（UCSB）、加州大学尔湾分校（UCI）、加州大学戴维斯分校（UCD）、加州大学圣克鲁兹分校（UCSC）、加州大学河滨分校（UCR）和加州大学美熹德分校（UCM）。（注：现今的加州大学并没有所谓的“主校区”，“分校”一词只是中文翻译误区）加州大学是世界最大的大学联邦体，其旗下大学在各项学术指标和排名中均名列前茅。这些校区互为独立又紧密联系，各自作为独立的大学而存在，共同组成了享誉全美乃至全世界的加州大学。,公立,美国,31,Computer Science and Engineering,"否,作为研究方向",博士,https://cse.ucsd.edu/graduate/doctoral-programs-computer-science-and-engineering,Jacob School of Engineering,Department of Computer Science and Engineering,,https://connect.grad.ucsd.edu/apply/?_gl=1*iwkn22*_ga*MTM5OTQ1ODM0Ny4xNzE0MjgxNjQ3*_ga_PWJGRGMV0T*MTcxNDY1MTY1NC44LjEuMTcxNDY1NDg2Mi4wLjAuMA..,4-7years,,否,37units,https://cse.ucsd.edu/graduate/doctoral-programs-computer-science-and-engineering,"providing a research-oriented education in preparation for a research, industrial, or entrepreneurial career",,否,否,否,https://cse.ucsd.edu/graduate/doctoral-programs-computer-science-and-engineering,https://ai.ucsd.edu/faculty,
39,马里兰大学学院园分校,"University of Maryland, College Park","马里兰大学，全称马里兰大学帕克分校（University of Maryland, College Park），简称 UMD或UMCP，始建于1856年，坐落于美国马里兰州，是世界知名学府，美国著名公立研究型大学。其位列2020U.S. News世界大学排名第51，2020QS美国大学排名第48，2020莫斯科国际大学排名第37，2020软科世界大学学术排名第53，2021U.S. News美国最佳大学排名第58，2019福布斯美国大学排行榜第63。大学一共孕育出6名诺贝尔奖得主 、15名普利策奖得主、60位国家科学院院士和数十位富布莱特学者。马里兰大学是美国大学协会和Universitas 21成员，是美国知名体育联盟十大联盟成员。马里兰大学下设13个学院，其科研及教研水平在全美乃至全世界均处于领先地位，学校有31项专业名列全美前10名，61项专业名列全美前15名，90项专业名列全美前25名。其尤以理工、商科而著名：在2018世界大学学术排名学科世界排名中，管理学世界排名第7，商学世界排名第10，电子工程学世界排名第18，经济学专业世界排名第17。该校校友参与创建了谷歌、安德玛等世界知名企业；并或于美国有线电视新闻网、洛克希德·马丁公司等企业出任CEO或总裁。",公立,美国,33,Computer Science-Machine Learning/Data Science,"否,作为研究方向",学士,https://academiccatalog.umd.edu/undergraduate/colleges-schools/computer-mathematical-natural-sciences/computer-science/computer-science-major/#text,"College of Computer, Mathematical and Natural Sciences",DEPARTMENT OF COMPUTER SCIENCE,,https://admissions.umd.edu/apply-now,Bachelor of Science in Computer Science,4years,否,120units,,/,"Graduates will be able to create, augment, debug, and test computer software. These skills will be built progressively through the courses in the introductory sequence and in some courses beyond that.
Graduates will develop mathematical and reasoning skills that are needed for computer science.
Graduates will be able to design and implement programming projects that are similar to those seen in the real world.
Graduates will gain skills in communication.
Academic Research (Optional): Graduates will be able to work independently on a project.",否,否,是,https://undergrad.cs.umd.edu/sites/undergrad.cs.umd.edu/files/images/uploads/2024/04/2401%20Computer%20Science%20Machine%20Learning%20Specialization.pdf,https://www.cs.umd.edu/researcharea/ai-and-robotics,https://cmns.umd.edu/sites/default/files/uploads/docs/four-year-plans/CMSCFourYearPlan.pdf
40,马里兰大学学院园分校,"University of Maryland, College Park","马里兰大学，全称马里兰大学帕克分校（University of Maryland, College Park），简称 UMD或UMCP，始建于1856年，坐落于美国马里兰州，是世界知名学府，美国著名公立研究型大学。其位列2020U.S. News世界大学排名第51，2020QS美国大学排名第48，2020莫斯科国际大学排名第37，2020软科世界大学学术排名第53，2021U.S. News美国最佳大学排名第58，2019福布斯美国大学排行榜第63。大学一共孕育出6名诺贝尔奖得主 、15名普利策奖得主、60位国家科学院院士和数十位富布莱特学者。马里兰大学是美国大学协会和Universitas 21成员，是美国知名体育联盟十大联盟成员。马里兰大学下设13个学院，其科研及教研水平在全美乃至全世界均处于领先地位，学校有31项专业名列全美前10名，61项专业名列全美前15名，90项专业名列全美前25名。其尤以理工、商科而著名：在2018世界大学学术排名学科世界排名中，管理学世界排名第7，商学世界排名第10，电子工程学世界排名第18，经济学专业世界排名第18。该校校友参与创建了谷歌、安德玛等世界知名企业；并或于美国有线电视新闻网、洛克希德·马丁公司等企业出任CEO或总裁。",公立,美国,33,Computer Science-AI/Robotics,"否,作为研究方向",学术型硕士,https://academiccatalog.umd.edu/graduate/programs/computer-science-cmsc/#text,"College of Computer, Mathematical, and Natural Sciences",DEPARTMENT OF COMPUTER SCIENCE,ranked among the top in the nation and in the top ten among public universities.,https://www.cs.umd.edu/grad/catalog#applying,Master of Science in Computer Science,2years,否,30 units,https://gradschool.umd.edu/students/academic-progress/thesis-and-dissertation-filing,our research mission creates new knowledge and prepares the next generation of knowledge producers,/,否,是,否,https://cmns.umd.edu/graduate/science-academy/data-science/masters,https://www.cs.umd.edu/researcharea/ai-and-robotics,
41,马里兰大学学院园分校,"University of Maryland, College Park","马里兰大学，全称马里兰大学帕克分校（University of Maryland, College Park），简称 UMD或UMCP，始建于1856年，坐落于美国马里兰州，是世界知名学府，美国著名公立研究型大学。其位列2020U.S. News世界大学排名第51，2020QS美国大学排名第48，2020莫斯科国际大学排名第37，2020软科世界大学学术排名第53，2021U.S. News美国最佳大学排名第58，2019福布斯美国大学排行榜第63。大学一共孕育出6名诺贝尔奖得主 、15名普利策奖得主、60位国家科学院院士和数十位富布莱特学者。马里兰大学是美国大学协会和Universitas 21成员，是美国知名体育联盟十大联盟成员。马里兰大学下设13个学院，其科研及教研水平在全美乃至全世界均处于领先地位，学校有31项专业名列全美前10名，61项专业名列全美前15名，90项专业名列全美前25名。其尤以理工、商科而著名：在2018世界大学学术排名学科世界排名中，管理学世界排名第7，商学世界排名第10，电子工程学世界排名第18，经济学专业世界排名第19。该校校友参与创建了谷歌、安德玛等世界知名企业；并或于美国有线电视新闻网、洛克希德·马丁公司等企业出任CEO或总裁。",公立,美国,33,Computer Science-AI/Robotics,"否,作为研究方向",博士,https://academiccatalog.umd.edu/graduate/programs/computer-science-cmsc/computer-science-phd/,"College of Computer, Mathematical, and Natural Sciences",DEPARTMENT OF COMPUTER SCIENCE,ranked among the top in the nation and in the top ten among public universities.,https://www.cs.umd.edu/grad/catalog#applying,Doctor of Philosophy  in Computer Science,5-6 years,否,37units,https://gradschool.umd.edu/students/academic-progress/thesis-and-dissertation-filing,/,/,否,是,否,https://cmns.umd.edu/graduate/science-academy/data-science/masters,https://www.cs.umd.edu/researcharea/ai-and-robotics,
`;

export default function getCSVData() {
	return csv_json(csvdata);
}
